In [1]:
import numpy as np

In [2]:
file_input = 'input.txt'
#file_input = 'input_test.txt'

with open(file_input,'r') as f:
    lines = f.readlines()

# Part1

In [3]:
lines

['6110\n',
 '2550\n',
 '6915\n',
 '5699\n',
 '4954\n',
 '5093\n',
 '3141\n',
 '5939\n',
 '4177\n',
 '3544\n',
 '5438\n',
 '5391\n',
 '3019\n',
 '\n',
 '4691\n',
 '6961\n',
 '7515\n',
 '4545\n',
 '11145\n',
 '8346\n',
 '9225\n',
 '\n',
 '9005\n',
 '2121\n',
 '4267\n',
 '1808\n',
 '3305\n',
 '9701\n',
 '1419\n',
 '\n',
 '7178\n',
 '4921\n',
 '6687\n',
 '1918\n',
 '4856\n',
 '4538\n',
 '2786\n',
 '5071\n',
 '2689\n',
 '1803\n',
 '5763\n',
 '\n',
 '12515\n',
 '15649\n',
 '17846\n',
 '14135\n',
 '\n',
 '3290\n',
 '2875\n',
 '1184\n',
 '3166\n',
 '3473\n',
 '1683\n',
 '2706\n',
 '6297\n',
 '2900\n',
 '1684\n',
 '4688\n',
 '3074\n',
 '\n',
 '3729\n',
 '6105\n',
 '7107\n',
 '7027\n',
 '5390\n',
 '11429\n',
 '8245\n',
 '\n',
 '13381\n',
 '12304\n',
 '20944\n',
 '\n',
 '18485\n',
 '\n',
 '2108\n',
 '5008\n',
 '5779\n',
 '3539\n',
 '1633\n',
 '3957\n',
 '5475\n',
 '1345\n',
 '1526\n',
 '1809\n',
 '4355\n',
 '3237\n',
 '5006\n',
 '2573\n',
 '4353\n',
 '\n',
 '1212\n',
 '5163\n',
 '3415\n',
 '3937\

In [4]:
elves_cal=[]

elf0 = []
#Separate calories for each elf
for line0 in lines:
    if line0 != '\n':
        calories=int(line0)
        elf0.append(calories)
    else:
        #print('empty line, next elf')
        elves_cal.append( np.array(elf0) )

        elf0=[] #Resets
if len(elf0)>0:
    elves_cal.append( np.array(elf0) ) #dont forget last line

elves_cal_np = np.array(elves_cal)


C:\Users\Luis-work\AppData\Local\Temp\ipykernel_24492\2063610742.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  elves_cal_np = np.array(elves_cal)


In [5]:
elves_cal_np

array([array([6110, 2550, 6915, 5699, 4954, 5093, 3141, 5939, 4177, 3544, 5438,
              5391, 3019])                                                     ,
       array([ 4691,  6961,  7515,  4545, 11145,  8346,  9225]),
       array([9005, 2121, 4267, 1808, 3305, 9701, 1419]),
       array([7178, 4921, 6687, 1918, 4856, 4538, 2786, 5071, 2689, 1803, 5763]),
       array([12515, 15649, 17846, 14135]),
       array([3290, 2875, 1184, 3166, 3473, 1683, 2706, 6297, 2900, 1684, 4688,
              3074])                                                           ,
       array([ 3729,  6105,  7107,  7027,  5390, 11429,  8245]),
       array([13381, 12304, 20944]), array([18485]),
       array([2108, 5008, 5779, 3539, 1633, 3957, 5475, 1345, 1526, 1809, 4355,
              3237, 5006, 2573, 4353])                                         ,
       array([1212, 5163, 3415, 3937, 2300, 3454, 4499, 3970, 5106, 3476, 5231,
              5849, 5685, 3991])                                      

In [6]:
elves_sumcal = np.array([np.sum(elf0) for elf0 in elves_cal_np])

In [7]:
elves_sumcal

array([61970, 52428, 31626, 48210, 60145, 37020, 49032, 46629, 18485,
       51703, 57288, 51207, 49586, 57365, 40327, 19535, 34787, 66239,
       43148, 57024, 51705, 36761, 57391, 55140, 29288, 41162, 66606,
       39859, 53776, 44474, 41504, 40668, 57585, 47552, 46545, 53296,
       32949, 38325, 42209, 56391, 42741, 25565, 44563, 45060, 49961,
       39613, 42774, 48067, 45671, 31243, 51199, 55550, 29477, 60744,
       56591, 58659, 47474, 56887, 48901, 37718, 45512, 26167, 52335,
       38888, 19530, 30897, 45583, 54729, 16064, 56843, 51197, 41067,
       20546, 32304, 37957, 57943, 30159, 51557, 59642, 55242, 44828,
       48560, 45472, 49792, 43225, 45370, 34019, 51977,  9498, 53987,
       19237, 34384, 41736, 58303, 36635, 42851, 47719, 49177, 49633,
       52047, 56660, 54383, 57199, 29021, 55605, 52347, 54232, 50966,
       36748, 52935, 41308, 36286, 53684, 47391, 41872, 43405, 33721,
       45622, 42649, 50115, 54586, 43888, 47902, 49527, 51410, 58910,
       47132, 34648,

In [8]:
elf_max_cal = np.max(elves_sumcal)
elf_max_cal #ok

69501

# Part2

Get the three most calories elves

In [9]:
cal_sort = np.sort(elves_sumcal)
cal_sort

array([ 7780,  8445,  8687,  9498,  9604, 16064, 18485, 19237, 19530,
       19535, 20546, 21170, 21400, 21781, 22115, 23942, 25253, 25565,
       26167, 26917, 28254, 29021, 29047, 29096, 29288, 29380, 29477,
       29773, 29989, 30159, 30332, 30897, 31243, 31313, 31484, 31626,
       32304, 32949, 33448, 33452, 33721, 34019, 34025, 34078, 34384,
       34648, 34787, 34886, 35191, 35648, 35805, 36182, 36286, 36635,
       36748, 36761, 37009, 37020, 37608, 37677, 37718, 37957, 38325,
       38794, 38888, 39613, 39859, 39869, 40068, 40327, 40513, 40668,
       41038, 41067, 41162, 41240, 41308, 41504, 41736, 41771, 41872,
       41974, 41993, 42005, 42074, 42128, 42209, 42368, 42649, 42741,
       42774, 42833, 42851, 42902, 43148, 43225, 43231, 43301, 43343,
       43399, 43405, 43418, 43671, 43777, 43888, 44474, 44563, 44828,
       45042, 45060, 45300, 45370, 45415, 45433, 45472, 45512, 45527,
       45530, 45583, 45622, 45629, 45671, 45899, 46465, 46468, 46477,
       46545, 46629,

sum of 3 most

In [10]:
sum_3_most = np.sum(cal_sort[-3:])
sum_3_most

202346