In [1]:
import numpy as np

In [2]:
#filename = "data_test.txt"
filename = "data.txt"

In [3]:
with open(filename, "r") as f:
    lines = f.readlines()

In [4]:
lines

['be cfbegad cbdgef fgaecd cgeb fdcge agebfd fecdb fabcd edb | fdgacbe cefdb cefbgd gcbe\n',
 'edbfga begcd cbg gc gcadebf fbgde acbgfd abcde gfcbed gfec | fcgedb cgb dgebacf gc\n',
 'fgaebd cg bdaec gdafb agbcfd gdcbef bgcad gfac gcb cdgabef | cg cg fdcagb cbg\n',
 'fbegcd cbd adcefb dageb afcb bc aefdc ecdab fgdeca fcdbega | efabcd cedba gadfec cb\n',
 'aecbfdg fbg gf bafeg dbefa fcge gcbea fcaegb dgceab fcbdga | gecf egdcabf bgf bfgea\n',
 'fgeab ca afcebg bdacfeg cfaedg gcfdb baec bfadeg bafgc acf | gebdcfa ecba ca fadegcb\n',
 'dbcfg fgd bdegcaf fgec aegbdf ecdfab fbedc dacgb gdcebf gf | cefg dcbef fcge gbcadfe\n',
 'bdfegc cbegaf gecbf dfcage bdacg ed bedf ced adcbefg gebcd | ed bcgafe cdgba cbgef\n',
 'egadfb cdbfeg cegd fecab cgb gbdefca cg fgcdab egfdb bfceg | gbdfcae bgc cg cgb\n',
 'gcafb gcf dcaebfg ecagb gf abcdeg gaef cafbge fdbac fegbdc | fgae cfgab fg bagce\n']

In [5]:
#Get the right side
leftside = []
rightside = []
for l in lines:
    left,right = l.strip().split(' | ')
    leftside.append(left)
    rightside.append(right)


In [6]:
leftside

['be cfbegad cbdgef fgaecd cgeb fdcge agebfd fecdb fabcd edb',
 'edbfga begcd cbg gc gcadebf fbgde acbgfd abcde gfcbed gfec',
 'fgaebd cg bdaec gdafb agbcfd gdcbef bgcad gfac gcb cdgabef',
 'fbegcd cbd adcefb dageb afcb bc aefdc ecdab fgdeca fcdbega',
 'aecbfdg fbg gf bafeg dbefa fcge gcbea fcaegb dgceab fcbdga',
 'fgeab ca afcebg bdacfeg cfaedg gcfdb baec bfadeg bafgc acf',
 'dbcfg fgd bdegcaf fgec aegbdf ecdfab fbedc dacgb gdcebf gf',
 'bdfegc cbegaf gecbf dfcage bdacg ed bedf ced adcbefg gebcd',
 'egadfb cdbfeg cegd fecab cgb gbdefca cg fgcdab egfdb bfceg',
 'gcafb gcf dcaebfg ecagb gf abcdeg gaef cafbge fdbac fegbdc']

In [7]:
rightside

['fdgacbe cefdb cefbgd gcbe',
 'fcgedb cgb dgebacf gc',
 'cg cg fdcagb cbg',
 'efabcd cedba gadfec cb',
 'gecf egdcabf bgf bfgea',
 'gebdcfa ecba ca fadegcb',
 'cefg dcbef fcge gbcadfe',
 'ed bcgafe cdgba cbgef',
 'gbdfcae bgc cg cgb',
 'fgae cfgab fg bagce']

In [8]:
def splitBySpace(s):
    return s.split(' ')

In [20]:
inputdigits = np.array( list(map(splitBySpace,leftside)))
inputdigits

array([['be', 'cfbegad', 'cbdgef', 'fgaecd', 'cgeb', 'fdcge', 'agebfd',
        'fecdb', 'fabcd', 'edb'],
       ['edbfga', 'begcd', 'cbg', 'gc', 'gcadebf', 'fbgde', 'acbgfd',
        'abcde', 'gfcbed', 'gfec'],
       ['fgaebd', 'cg', 'bdaec', 'gdafb', 'agbcfd', 'gdcbef', 'bgcad',
        'gfac', 'gcb', 'cdgabef'],
       ['fbegcd', 'cbd', 'adcefb', 'dageb', 'afcb', 'bc', 'aefdc',
        'ecdab', 'fgdeca', 'fcdbega'],
       ['aecbfdg', 'fbg', 'gf', 'bafeg', 'dbefa', 'fcge', 'gcbea',
        'fcaegb', 'dgceab', 'fcbdga'],
       ['fgeab', 'ca', 'afcebg', 'bdacfeg', 'cfaedg', 'gcfdb', 'baec',
        'bfadeg', 'bafgc', 'acf'],
       ['dbcfg', 'fgd', 'bdegcaf', 'fgec', 'aegbdf', 'ecdfab', 'fbedc',
        'dacgb', 'gdcebf', 'gf'],
       ['bdfegc', 'cbegaf', 'gecbf', 'dfcage', 'bdacg', 'ed', 'bedf',
        'ced', 'adcbefg', 'gebcd'],
       ['egadfb', 'cdbfeg', 'cegd', 'fecab', 'cgb', 'gbdefca', 'cg',
        'fgcdab', 'egfdb', 'bfceg'],
       ['gcafb', 'gcf', 'dcaebfg', 'ecagb', 'g

In [19]:
outputdigits = np.array( list(map(splitBySpace,rightside)))

In [ ]:
'''
Digits determination

nchars can tell the following digits

nchar | digit
2       1
3       7
4       4
5       2,3,5
6       0,6,9
7       8

Identification

digit 3, is the only one that shares the same segments as digit 1
digit 2 and 5, compare with segments in 4. Digit 5 shares +1 segment compared with digit 2
digit 2, compare with segments in 4, shares 2 segments
digit 5, compare with segments in 4, shares 3 segments
digit 9, all segments are shared with digit 4. Compare with segments in digit 4, shares all 4 segments
digit 0, Compare with segments in digit 1, shares 2 segments
digit 6, Compare with segments in digit 1, shares 1 segments

'''

In [23]:
#Need to determine the translation line-by-line (per entry)
#First line test
inputline0 = inputdigits[0]
inputline0

array(['be', 'cfbegad', 'cbdgef', 'fgaecd', 'cgeb', 'fdcge', 'agebfd',
       'fecdb', 'fabcd', 'edb'], dtype='<U7')

In [32]:
inp_nchar = np.char.str_len(inputline0)
inp_nchar

array([2, 7, 6, 6, 4, 5, 6, 5, 5, 3])

In [78]:
#Find index for obvious ones
d1_arg = np.argwhere(inp_nchar == 2)[0][0]
d4_arg = np.argwhere(inp_nchar == 4)[0][0]
d7_arg = np.argwhere(inp_nchar == 3)[0][0]
d8_arg = np.argwhere(inp_nchar == 7)[0][0]

In [91]:
print(f"arguments of d1, d4, d7, d8 : {d1_arg},{ d4_arg},{d7_arg},{d8_arg}")

arguments of d1, d4, d7, d8 : 0,4,9,1


In [80]:
segm4 = inputline0[d4_arg]
segm4

'cgeb'

In [81]:
segm4_sorted = sorted(segm4)
segm4_sorted

['b', 'c', 'e', 'g']

In [92]:
segm4 = inputline0[d4_arg]
segm4_sorted = sorted(segm4)
def compareWithDigit4(segm):
    n=0
    for c in segm:
        if segm4_sorted.count(c)>0:
            n+=1
    return n

segm1_sorted = sorted(inputline0[d1_arg])
def compareWithDigit1(segm):
    n=0
    for c in segm:
        if segm1_sorted.count(c)>0:
            n+=1
    return n

In [93]:
nchars_of_5 = np.argwhere(inp_nchar == 5)
nchars_of_5

array([[5],
       [7],
       [8]], dtype=int64)

In [94]:
arg_nchar5_0 = nchars_of_5[0][0]
arg_nchar5_0

5

In [95]:
segm5 = inputline0[arg_nchar5_0]
segm5

'fdcge'

In [96]:
n5 = compareWithDigit4(segm5)
n5
#Seems to be working

3

In [102]:
d3_arg=None
d2_arg=None
d5_arg=None

for a in nchars_of_5:
    arg=a[0]
    segm = inputline0[arg]
    #Compare with segments of d1
    n1 = compareWithDigit1(segm)
    if n1==2:
        #Digit is 3
        d3_arg = arg
    else:
        n5 = compareWithDigit4(segm)
        if n5==2:
            #is 2
            d2_arg=arg
        else:
            d5_arg=arg

print(f"arguments of 2,3,5 : {d2_arg,d3_arg,d5_arg}")

arguments of 2,3,5 : (8, 7, 5)


In [98]:
nchars_of_6 = np.argwhere(inp_nchar == 6)

In [99]:
nchars_of_6

array([[2],
       [3],
       [6]], dtype=int64)

In [101]:
d0_arg=None
d6_arg=None
d9_arg=None

for a in nchars_of_6:
    arg=a[0]
    segm = inputline0[arg]
    print(f"segm = {segm}")
    #Compare with segments of d1
    n4 = compareWithDigit4(segm)
    print(f"n4 = {n4}")
    if n4==4:
        print("digit is 9")
        d9_arg=arg
    else:
        n1 = compareWithDigit1(segm)
        print(f"n1 = {n1}")
        if n1==1:
            print("digit is 6")
            d6_arg = arg
        else:
            print("digit is 0")
            d0_arg=arg

print(f"arguments of 0,6,9 : {d0_arg,d6_arg,d9_arg}")

segm = cbdgef
n4 = 4
digit is 9
segm = fgaecd
n4 = 3
n1 = 1
digit is 6
segm = agebfd
n4 = 3
n1 = 2
digit is 0
arguments of 0,6,9 : (6, 3, 2)


In [118]:
def sortCharacters(s):
    return ''.join(sorted(s))

In [127]:
#Now that segments have been identified, create a dictionary

segm_to_digit_dict ={
    sortCharacters(inputline0[d0_arg]) : '0' ,
    sortCharacters(inputline0[d1_arg]) : '1' ,
    sortCharacters(inputline0[d2_arg]) : '2' ,
    sortCharacters(inputline0[d3_arg]) : '3' ,
    sortCharacters(inputline0[d4_arg]) : '4' ,
    sortCharacters(inputline0[d5_arg]) : '5' ,
    sortCharacters(inputline0[d6_arg]) : '6' ,
    sortCharacters(inputline0[d7_arg]) : '7' ,
    sortCharacters(inputline0[d8_arg]) : '8' ,
    sortCharacters(inputline0[d9_arg]) : '9'
}

In [128]:
segm_to_digit_dict

{'abdefg': '0',
 'be': '1',
 'abcdf': '2',
 'bcdef': '3',
 'bceg': '4',
 'cdefg': '5',
 'acdefg': '6',
 'bde': '7',
 'abcdefg': '8',
 'bcdefg': '9'}

In [129]:
#Get the digits
outputdigits[0]

array(['fdgacbe', 'cefdb', 'cefbgd', 'gcbe'], dtype='<U7')

In [130]:
def convertSegmToDigits(segm):
    s0 = sortCharacters(segm)
    return(segm_to_digit_dict[s0])

In [132]:
digits = list(map(convertSegmToDigits,outputdigits[0]))

In [133]:
digits

['8', '3', '9', '4']

In [135]:
#Put digits together to form a number
value = int(''.join(digits)) #OK

8394

# Run from here after getting lines

In [6]:
#Do this for all the lines in the data
values = []

for line in lines:
    print(f"line: {line}")
    left,right = line.strip().split(' | ')
    inputline0 = left.split(' ')
    outputline0 = right.split(' ')

    inp_nchar = np.char.str_len(inputline0)
    d1_arg = np.argwhere(inp_nchar == 2)[0][0]
    d4_arg = np.argwhere(inp_nchar == 4)[0][0]
    d7_arg = np.argwhere(inp_nchar == 3)[0][0]
    d8_arg = np.argwhere(inp_nchar == 7)[0][0]
    print(f"arguments of d1, d4, d7, d8 : {d1_arg},{ d4_arg},{d7_arg},{d8_arg}")

    segm4 = inputline0[d4_arg]
    segm4_sorted = sorted(segm4)
    def compareWithDigit4(segm):
        n=0
        for c in segm:
            if segm4_sorted.count(c)>0:
                n+=1
        return n

    segm1_sorted = sorted(inputline0[d1_arg])
    def compareWithDigit1(segm):
        n=0
        for c in segm:
            if segm1_sorted.count(c)>0:
                n+=1
        return n
    
    nchars_of_5 = np.argwhere(inp_nchar == 5)
    #arg_nchar5_0 = nchars_of_5[0][0]
    #segm5 = inputline0[arg_nchar5_0]

    d3_arg=None
    d2_arg=None
    d5_arg=None

    for a in nchars_of_5:
        arg=a[0]
        segm = inputline0[arg]
        #Compare with segments of d1
        n1 = compareWithDigit1(segm)
        if n1==2:
            #Digit is 3
            d3_arg = arg
        else:
            n5 = compareWithDigit4(segm)
            if n5==2:
                #is 2
                d2_arg=arg
            else:
                d5_arg=arg
    print(f"arguments of 2,3,5 : {d2_arg,d3_arg,d5_arg}")

    nchars_of_6 = np.argwhere(inp_nchar == 6)

    d0_arg=None
    d6_arg=None
    d9_arg=None

    for a in nchars_of_6:
        arg=a[0]
        segm = inputline0[arg]
        print(f"segm = {segm}")
        #Compare with segments of d1
        n4 = compareWithDigit4(segm)
        print(f"n4 = {n4}")
        if n4==4:
            print("digit is 9")
            d9_arg=arg
        else:
            n1 = compareWithDigit1(segm)
            print(f"n1 = {n1}")
            if n1==1:
                print("digit is 6")
                d6_arg = arg
            else:
                print("digit is 0")
                d0_arg=arg

    print(f"arguments of 0,6,9 : {d0_arg,d6_arg,d9_arg}")

    def _sortCharacters(s):
        return ''.join(sorted(s))

    segm_to_digit_dict ={
        _sortCharacters(inputline0[d0_arg]) : '0' ,
        _sortCharacters(inputline0[d1_arg]) : '1' ,
        _sortCharacters(inputline0[d2_arg]) : '2' ,
        _sortCharacters(inputline0[d3_arg]) : '3' ,
        _sortCharacters(inputline0[d4_arg]) : '4' ,
        _sortCharacters(inputline0[d5_arg]) : '5' ,
        _sortCharacters(inputline0[d6_arg]) : '6' ,
        _sortCharacters(inputline0[d7_arg]) : '7' ,
        _sortCharacters(inputline0[d8_arg]) : '8' ,
        _sortCharacters(inputline0[d9_arg]) : '9'
    }

    def _convertSegmToDigits(segm):
        s0 = _sortCharacters(segm)
        return(segm_to_digit_dict[s0])

    digits = list(map(_convertSegmToDigits,outputline0))
    print(f"converted out digits: {digits}")
    value = int(''.join(digits))
    
    values.append(value)


line: ec cabfe afebd dbagef afbcg feabcd cdef eafdcbg ecb caegdb | ceb ecb febac ec

arguments of d1, d4, d7, d8 : 0,6,8,7
arguments of 2,3,5 : (4, 1, 2)
segm = dbagef
n4 = 3
n1 = 1
digit is 6
segm = feabcd
n4 = 4
digit is 9
segm = caegdb
n4 = 3
n1 = 2
digit is 0
arguments of 0,6,9 : (9, 3, 5)
converted out digits: ['7', '7', '3', '1']
line: acfdg ea baec dgbafec cfebg efa cfebgd dfbaeg egcaf abecfg | bgcdfe ebac cadgf dceagfb

arguments of d1, d4, d7, d8 : 1,2,5,3
arguments of 2,3,5 : (0, 8, 4)
segm = cfebgd
n4 = 3
n1 = 1
digit is 6
segm = dfbaeg
n4 = 3
n1 = 2
digit is 0
segm = abecfg
n4 = 4
digit is 9
arguments of 0,6,9 : (7, 6, 9)
converted out digits: ['6', '4', '2', '8']
line: gfed caefd dcegaf ge daegc bcdag dfagbce cfbead gce afbegc | ceadg edfg gdbca fcead

arguments of d1, d4, d7, d8 : 3,0,8,6
arguments of 2,3,5 : (5, 4, 1)
segm = dcegaf
n4 = 4
digit is 9
segm = cfbead
n4 = 3
n1 = 1
digit is 6
segm = afbegc
n4 = 3
n1 = 2
digit is 0
arguments of 0,6,9 : (9, 7, 2)
converted out 

In [7]:
#Sum of outvalues
values_np = np.array(values)
np.sum(values_np) #OK

1055164