In [1]:
import numpy as np

In [2]:
#filename = "data_test.txt"
filename = "data.txt"

In [3]:
with open(filename, "r") as f:
    lines = f.readlines()

In [4]:
lines

['ec cabfe afebd dbagef afbcg feabcd cdef eafdcbg ecb caegdb | ceb ecb febac ec\n',
 'acfdg ea baec dgbafec cfebg efa cfebgd dfbaeg egcaf abecfg | bgcdfe ebac cadgf dceagfb\n',
 'gfed caefd dcegaf ge daegc bcdag dfagbce cfbead gce afbegc | ceadg edfg gdbca fcead\n',
 'ea dgfcae feba cae efbcagd cagfb gedcb gbfcad gebca afbceg | facbgde cegdbaf cgabe degcb\n',
 'gcbfed bdf cbdfgea fgeabc dcfab caefb db caebdf abde fgdca | fdb fabce dbacf afceb\n',
 'bacf afg egfab dcbgef bcegdaf efgbac efcgda fa gbfce gebad | edgba bfacged af fdacbeg\n',
 'adgef bagcf cdea adfebg dfgca adfgec cd fcdgbe cdf cdfegab | afgdbe facdg gdfbeac dcea\n',
 'cdgeb cd cdb gfecbda adgcbe bcdfag aecd bfceg edbfga agdbe | bdc dbeacg dceabg gcedb\n',
 'ae cdbeg gefcdb eca ebgfac dcbafeg deag abcde facbd becadg | aec cbaedg aec deag\n',
 'gabfc cdfbe ea dbcfeag aebfgc befagd ebfac aeb gaec bagdfc | ea gbadfc dgbfca decbf\n',
 'bcad cd cfbge cegabdf fcdeb defabc gebadf fdc adfbe ecadfg | dc fcd egdcfa dc\n',
 'begcda cbf

In [5]:
#Get the right side
leftside = []
rightside = []
for l in lines:
    left,right = l.strip().split(' | ')
    leftside.append(left)
    rightside.append(right)


In [6]:
leftside

['ec cabfe afebd dbagef afbcg feabcd cdef eafdcbg ecb caegdb',
 'acfdg ea baec dgbafec cfebg efa cfebgd dfbaeg egcaf abecfg',
 'gfed caefd dcegaf ge daegc bcdag dfagbce cfbead gce afbegc',
 'ea dgfcae feba cae efbcagd cagfb gedcb gbfcad gebca afbceg',
 'gcbfed bdf cbdfgea fgeabc dcfab caefb db caebdf abde fgdca',
 'bacf afg egfab dcbgef bcegdaf efgbac efcgda fa gbfce gebad',
 'adgef bagcf cdea adfebg dfgca adfgec cd fcdgbe cdf cdfegab',
 'cdgeb cd cdb gfecbda adgcbe bcdfag aecd bfceg edbfga agdbe',
 'ae cdbeg gefcdb eca ebgfac dcbafeg deag abcde facbd becadg',
 'gabfc cdfbe ea dbcfeag aebfgc befagd ebfac aeb gaec bagdfc',
 'bcad cd cfbge cegabdf fcdeb defabc gebadf fdc adfbe ecadfg',
 'begcda cbf egacb fc ebcaf baefd gabdfc gfce gaecfb acgdfeb',
 'fbgce dagcbe eafcbg bcgdfe geacdfb efdb dcgaf dge de gfdec',
 'fdgae fce cdeab gcfd fc efdca eadfgb fcgdae efdcbag gaefcb',
 'cfag cadgfb cf cfd cdbgf gaebdc bgfde cgbfead befacd cadbg',
 'gebf edbcga edcabgf cfabed aeg agcfeb fgaec ge cgadf 

In [7]:
rightside

['ceb ecb febac ec',
 'bgcdfe ebac cadgf dceagfb',
 'ceadg edfg gdbca fcead',
 'facbgde cegdbaf cgabe degcb',
 'fdb fabce dbacf afceb',
 'edgba bfacged af fdacbeg',
 'afgdbe facdg gdfbeac dcea',
 'bdc dbeacg dceabg gcedb',
 'aec cbaedg aec deag',
 'ea gbadfc dgbfca decbf',
 'dc fcd egdcfa dc',
 'bdegfca cf fc acbdeg',
 'cgbfe bagced daecbgf bfde',
 'efbdag fgeda adbfeg befagc',
 'gcbda fcd bfged dcf',
 'abcgdfe gafbce cfagbe bgfe',
 'bcagedf bfea acdbefg faceg',
 'caebf dcf dcf ebcagf',
 'adbg gdba ga aeg',
 'ec gadbfc cbgfa bgcadef',
 'gb edgbcaf gbc cbg',
 'gefa ecdbafg gbdfc cegfb',
 'gebafc befcga gfadbe cgeab',
 'acdef gbcdef agcf cgbdaef',
 'bcf cfdegba fb dfcbe',
 'afdge db bcgaed cbaefd',
 'gadec cgb efgdacb gdacb',
 'gbefda efacd bd dfb',
 'afdge eac gaefd cdega',
 'gfabdc edf fage cdabe',
 'ecagf bedc dac dc',
 'ag bfgec ag cdbeaf',
 'db dbe faecdbg dbe',
 'ed cfeabg aged dgecabf',
 'fge afceb eacfg agecd',
 'cga afgce gdfc agc',
 'eadcfgb aec ace aec',
 'befdcga aegfbc efbca

In [8]:
def splitBySpace(s):
    return s.split(' ')

In [9]:
outputdigits = np.array( list(map(splitBySpace,rightside)))

In [10]:
outputdigits

array([['ceb', 'ecb', 'febac', 'ec'],
       ['bgcdfe', 'ebac', 'cadgf', 'dceagfb'],
       ['ceadg', 'edfg', 'gdbca', 'fcead'],
       ['facbgde', 'cegdbaf', 'cgabe', 'degcb'],
       ['fdb', 'fabce', 'dbacf', 'afceb'],
       ['edgba', 'bfacged', 'af', 'fdacbeg'],
       ['afgdbe', 'facdg', 'gdfbeac', 'dcea'],
       ['bdc', 'dbeacg', 'dceabg', 'gcedb'],
       ['aec', 'cbaedg', 'aec', 'deag'],
       ['ea', 'gbadfc', 'dgbfca', 'decbf'],
       ['dc', 'fcd', 'egdcfa', 'dc'],
       ['bdegfca', 'cf', 'fc', 'acbdeg'],
       ['cgbfe', 'bagced', 'daecbgf', 'bfde'],
       ['efbdag', 'fgeda', 'adbfeg', 'befagc'],
       ['gcbda', 'fcd', 'bfged', 'dcf'],
       ['abcgdfe', 'gafbce', 'cfagbe', 'bgfe'],
       ['bcagedf', 'bfea', 'acdbefg', 'faceg'],
       ['caebf', 'dcf', 'dcf', 'ebcagf'],
       ['adbg', 'gdba', 'ga', 'aeg'],
       ['ec', 'gadbfc', 'cbgfa', 'bgcadef'],
       ['gb', 'edgbcaf', 'gbc', 'cbg'],
       ['gefa', 'ecdbafg', 'gbdfc', 'cegfb'],
       ['gebafc', 'befcga', 'gfad

In [11]:
outputdigits_nchars = np.char.str_len(outputdigits)
outputdigits_nchars

array([[3, 3, 5, 2],
       [6, 4, 5, 7],
       [5, 4, 5, 5],
       [7, 7, 5, 5],
       [3, 5, 5, 5],
       [5, 7, 2, 7],
       [6, 5, 7, 4],
       [3, 6, 6, 5],
       [3, 6, 3, 4],
       [2, 6, 6, 5],
       [2, 3, 6, 2],
       [7, 2, 2, 6],
       [5, 6, 7, 4],
       [6, 5, 6, 6],
       [5, 3, 5, 3],
       [7, 6, 6, 4],
       [7, 4, 7, 5],
       [5, 3, 3, 6],
       [4, 4, 2, 3],
       [2, 6, 5, 7],
       [2, 7, 3, 3],
       [4, 7, 5, 5],
       [6, 6, 6, 5],
       [5, 6, 4, 7],
       [3, 7, 2, 5],
       [5, 2, 6, 6],
       [5, 3, 7, 5],
       [6, 5, 2, 3],
       [5, 3, 5, 5],
       [6, 3, 4, 5],
       [5, 4, 3, 2],
       [2, 5, 2, 6],
       [2, 3, 7, 3],
       [2, 6, 4, 7],
       [3, 5, 5, 5],
       [3, 5, 4, 3],
       [7, 3, 3, 3],
       [7, 6, 6, 3],
       [2, 7, 4, 2],
       [7, 5, 4, 3],
       [7, 7, 3, 7],
       [3, 5, 6, 6],
       [5, 2, 4, 6],
       [7, 2, 2, 6],
       [5, 3, 2, 3],
       [2, 6, 5, 4],
       [5, 7, 2, 5],
       [2, 7,

In [12]:
out_digit1 = np.where(outputdigits_nchars == 2 ,1,0)
out_digit1

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0,

In [13]:
out_digit4 = np.where(outputdigits_nchars == 4 ,1,0)
out_digit4

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0,

In [14]:
out_digit7 = np.where(outputdigits_nchars == 3,1,0)
out_digit7

array([[1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [15]:
out_digit8 = np.where(outputdigits_nchars == 7 ,1,0)
out_digit8

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1,

In [16]:
print (f"1,4,7,8 : {np.sum(out_digit1)} , {np.sum(out_digit4)}, {np.sum(out_digit7)}, {np.sum(out_digit8)} " )

1,4,7,8 : 123 , 117, 121, 134 


In [17]:
total1478 = np.sum(out_digit1) + np.sum(out_digit4)+np.sum(out_digit7)+np.sum(out_digit8)
total1478 #OK

495