In [1]:
import numpy as np

In [2]:
#filename = "input_test.txt"
filename="input.txt"

In [3]:
with open(filename,"r") as f:
    crab_pos = np.fromfile(filename, sep=",",dtype=np.int32)

In [4]:
crab_pos

array([1101,    1,   29,   67, 1102,    0,    1,   65, 1008,   65,   35,
         66, 1005,   66,   28,    1,   67,   65,   20,    4,    0, 1001,
         65,    1,   65, 1106,    0,    8,   99,   35,   67,  101,   99,
        105,   32,  110,   39,  101,  115,  116,   32,  112,   97,  115,
         32,  117,  110,  101,   32,  105,  110,  116,   99,  111,  100,
        101,   32,  112,  114,  111,  103,  114,   97,  109,   10,  121,
        295, 1276,  124,  523,  395,  987,  355, 1668,  754,  139,  217,
        433,    1,  836,  467, 1384,   66,  390, 1278,  113,  114,  355,
        434,  396, 1050, 1552,  612,  793,  532,   26, 1340,  150,  455,
         83,  320,  587,  701,  429,  596,  154,    4, 1247,   55, 1376,
        507,  205, 1760,  774,  980,  485,   10,  161,  524,  213,  156,
         36,   56,  550,  429,  337,   76,   53,  276,  475, 1220, 1539,
         10,   53,   87,   32, 1280,  757,  447,  948,  983,  504,  998,
       1220,   27,    6, 1410,  118,  172,  467,   

In [5]:
#test a value for xp
xp=5

In [6]:
crab_pos_diff = np.abs(crab_pos-xp)
fuels = crab_pos_diff*(crab_pos_diff+1)/2 #https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_⋯
fuels

array([6.011560e+05, 1.000000e+01, 3.000000e+02, 1.953000e+03,
       6.022530e+05, 1.500000e+01, 1.000000e+01, 1.830000e+03,
       5.035060e+05, 1.830000e+03, 4.650000e+02, 1.891000e+03,
       5.005000e+05, 1.891000e+03, 2.760000e+02, 1.000000e+01,
       1.953000e+03, 1.830000e+03, 1.200000e+02, 1.000000e+00,
       1.500000e+01, 4.965060e+05, 1.830000e+03, 1.000000e+01,
       1.830000e+03, 6.066510e+05, 1.500000e+01, 6.000000e+00,
       4.465000e+03, 4.650000e+02, 1.953000e+03, 4.656000e+03,
       4.465000e+03, 5.050000e+03, 3.780000e+02, 5.565000e+03,
       5.950000e+02, 4.656000e+03, 6.105000e+03, 6.216000e+03,
       3.780000e+02, 5.778000e+03, 4.278000e+03, 6.105000e+03,
       3.780000e+02, 6.328000e+03, 5.565000e+03, 4.656000e+03,
       3.780000e+02, 5.050000e+03, 5.565000e+03, 6.216000e+03,
       4.465000e+03, 5.671000e+03, 4.560000e+03, 4.656000e+03,
       3.780000e+02, 5.778000e+03, 5.995000e+03, 5.671000e+03,
       4.851000e+03, 5.995000e+03, 4.278000e+03, 5.4600

In [7]:
total_fuel= np.sum(fuels)

In [8]:
total_fuel

202484337.0

In [9]:
def getTotalFuelForPos(xp):
    crab_pos_diff = np.abs(crab_pos-xp)
    fuels = crab_pos_diff*(crab_pos_diff+1)/2 #https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_⋯
    return np.sum(fuels)

In [10]:
#Vectorize previous function
getTotalFuelForPos_vect = np.vectorize(getTotalFuelForPos)

In [11]:
#Get the total fuel for all the positions available
xps = np.arange(np.max(crab_pos),dtype=np.int32)

total_fuels = getTotalFuelForPos_vect(xps)

In [12]:
total_fuels

array([2.04841789e+08, 2.04368290e+08, 2.03895799e+08, ...,
       1.13650670e+09, 1.13795219e+09, 1.13939868e+09])

In [13]:
total_fuels.min() #OK

92676646.0