In [1]:
import numpy as np

In [2]:
with open("data.txt","r") as f:
    text_lines = f.readlines()

In [3]:
text_lines

['14,30,18,8,3,10,77,4,48,67,28,38,63,43,62,12,68,88,54,32,17,21,83,64,97,53,24,2,60,96,86,23,20,93,65,34,45,46,42,49,71,9,61,16,31,1,29,40,59,87,95,41,39,27,6,25,19,58,80,81,50,79,73,15,70,37,92,94,7,55,85,98,5,84,99,26,66,57,82,75,22,89,74,36,11,76,56,33,13,72,35,78,47,91,51,44,69,0,90,52\n',
 '\n',
 '13 62 38 10 41\n',
 '93 59 60 74 75\n',
 '79 18 57 90 28\n',
 '56 76 34 96 84\n',
 '78 42 69 14 19\n',
 '\n',
 '96 38 62  8  7\n',
 '78 50 53 29 81\n',
 '88 45 34 58 52\n',
 '33 76 13 54 68\n',
 '59 95 10 80 63\n',
 '\n',
 '36 26 74 29 55\n',
 '43 87 46 70 21\n',
 ' 9 17 38 58 63\n',
 '56 79 85 51  2\n',
 '50 57 67 86  8\n',
 '\n',
 '29 78  3 24 79\n',
 '15 81 20  6 38\n',
 '97 41 28 42 82\n',
 '45 68 89 85 92\n',
 '48 33 40 62  4\n',
 '\n',
 '68 38 43  2 27\n',
 '74 92 49 11 22\n',
 '33 97 73 87 30\n',
 '42 28 60 39 67\n',
 ' 3 66 35 94 47\n',
 '\n',
 ' 6 65  2 30 88\n',
 '69  3 33 61 23\n',
 '62 40 37  7 43\n',
 '55 12 70 36 73\n',
 '15 20 85 38 44\n',
 '\n',
 '99 36 10 83 69\n',
 '31

In [4]:
#First line is the drawn balls
balls = list( map(int,text_lines[0].split(',')) )

In [5]:
balls

[14,
 30,
 18,
 8,
 3,
 10,
 77,
 4,
 48,
 67,
 28,
 38,
 63,
 43,
 62,
 12,
 68,
 88,
 54,
 32,
 17,
 21,
 83,
 64,
 97,
 53,
 24,
 2,
 60,
 96,
 86,
 23,
 20,
 93,
 65,
 34,
 45,
 46,
 42,
 49,
 71,
 9,
 61,
 16,
 31,
 1,
 29,
 40,
 59,
 87,
 95,
 41,
 39,
 27,
 6,
 25,
 19,
 58,
 80,
 81,
 50,
 79,
 73,
 15,
 70,
 37,
 92,
 94,
 7,
 55,
 85,
 98,
 5,
 84,
 99,
 26,
 66,
 57,
 82,
 75,
 22,
 89,
 74,
 36,
 11,
 76,
 56,
 33,
 13,
 72,
 35,
 78,
 47,
 91,
 51,
 44,
 69,
 0,
 90,
 52]

In [6]:
#Get the boards one by one

nboard=0
boards=[]
#boardline=0

import re

i=2
while i < len(text_lines):
    
    #print(text_lines[i].strip())
    line = text_lines[i].strip()

    if line=='':
        print("line is empty")
    else:
        #Read 5 lines
        def splitLineToListInts(s):
            s= s.strip()
            #print(s)
            ret  = list(map(int,re.split(' +', s ) ) )
            print(ret)
            return ret

        board=[]
        board.append( splitLineToListInts(text_lines[i] ) )
        i+=1
        board.append( splitLineToListInts(text_lines[i] ) )
        i+=1
        board.append( splitLineToListInts(text_lines[i] ) )
        i+=1
        board.append( splitLineToListInts(text_lines[i] ) )
        i+=1
        board.append( splitLineToListInts(text_lines[i] ) )

        boards.append( board )
        i+=1
        #print(f"i= {i}")
        #print(f"nboards = {len(boards)}")
    i+=1


[13, 62, 38, 10, 41]
[93, 59, 60, 74, 75]
[79, 18, 57, 90, 28]
[56, 76, 34, 96, 84]
[78, 42, 69, 14, 19]
[96, 38, 62, 8, 7]
[78, 50, 53, 29, 81]
[88, 45, 34, 58, 52]
[33, 76, 13, 54, 68]
[59, 95, 10, 80, 63]
[36, 26, 74, 29, 55]
[43, 87, 46, 70, 21]
[9, 17, 38, 58, 63]
[56, 79, 85, 51, 2]
[50, 57, 67, 86, 8]
[29, 78, 3, 24, 79]
[15, 81, 20, 6, 38]
[97, 41, 28, 42, 82]
[45, 68, 89, 85, 92]
[48, 33, 40, 62, 4]
[68, 38, 43, 2, 27]
[74, 92, 49, 11, 22]
[33, 97, 73, 87, 30]
[42, 28, 60, 39, 67]
[3, 66, 35, 94, 47]
[6, 65, 2, 30, 88]
[69, 3, 33, 61, 23]
[62, 40, 37, 7, 43]
[55, 12, 70, 36, 73]
[15, 20, 85, 38, 44]
[99, 36, 10, 83, 69]
[31, 58, 93, 87, 56]
[33, 25, 82, 59, 30]
[45, 86, 79, 12, 2]
[39, 57, 51, 53, 13]
[48, 46, 11, 20, 69]
[89, 9, 96, 45, 76]
[67, 78, 82, 6, 97]
[30, 41, 37, 32, 64]
[47, 31, 93, 29, 75]
[49, 93, 50, 83, 64]
[54, 4, 18, 1, 76]
[75, 30, 19, 78, 12]
[84, 55, 28, 3, 57]
[16, 77, 87, 25, 2]
[15, 57, 86, 92, 60]
[87, 66, 76, 12, 52]
[62, 74, 93, 88, 78]
[39, 13, 44, 

In [7]:
print(boards)

[[[13, 62, 38, 10, 41], [93, 59, 60, 74, 75], [79, 18, 57, 90, 28], [56, 76, 34, 96, 84], [78, 42, 69, 14, 19]], [[96, 38, 62, 8, 7], [78, 50, 53, 29, 81], [88, 45, 34, 58, 52], [33, 76, 13, 54, 68], [59, 95, 10, 80, 63]], [[36, 26, 74, 29, 55], [43, 87, 46, 70, 21], [9, 17, 38, 58, 63], [56, 79, 85, 51, 2], [50, 57, 67, 86, 8]], [[29, 78, 3, 24, 79], [15, 81, 20, 6, 38], [97, 41, 28, 42, 82], [45, 68, 89, 85, 92], [48, 33, 40, 62, 4]], [[68, 38, 43, 2, 27], [74, 92, 49, 11, 22], [33, 97, 73, 87, 30], [42, 28, 60, 39, 67], [3, 66, 35, 94, 47]], [[6, 65, 2, 30, 88], [69, 3, 33, 61, 23], [62, 40, 37, 7, 43], [55, 12, 70, 36, 73], [15, 20, 85, 38, 44]], [[99, 36, 10, 83, 69], [31, 58, 93, 87, 56], [33, 25, 82, 59, 30], [45, 86, 79, 12, 2], [39, 57, 51, 53, 13]], [[48, 46, 11, 20, 69], [89, 9, 96, 45, 76], [67, 78, 82, 6, 97], [30, 41, 37, 32, 64], [47, 31, 93, 29, 75]], [[49, 93, 50, 83, 64], [54, 4, 18, 1, 76], [75, 30, 19, 78, 12], [84, 55, 28, 3, 57], [16, 77, 87, 25, 2]], [[15, 57, 86

In [8]:
def convToOrder(i):
    index = balls.index(i)#
    return index

In [9]:
convToOrder(22)

80

In [10]:
boards_np = np.array(boards)

In [11]:
boards_np

array([[[13, 62, 38, 10, 41],
        [93, 59, 60, 74, 75],
        [79, 18, 57, 90, 28],
        [56, 76, 34, 96, 84],
        [78, 42, 69, 14, 19]],

       [[96, 38, 62,  8,  7],
        [78, 50, 53, 29, 81],
        [88, 45, 34, 58, 52],
        [33, 76, 13, 54, 68],
        [59, 95, 10, 80, 63]],

       [[36, 26, 74, 29, 55],
        [43, 87, 46, 70, 21],
        [ 9, 17, 38, 58, 63],
        [56, 79, 85, 51,  2],
        [50, 57, 67, 86,  8]],

       ...,

       [[ 5, 72, 83, 53, 49],
        [48,  6,  9, 38, 15],
        [99, 84, 90, 82, 70],
        [69, 85,  4, 67, 20],
        [87, 16, 61, 21, 39]],

       [[18, 43, 78,  0, 77],
        [91, 37, 88, 32, 71],
        [15, 54,  2, 62, 17],
        [30, 98, 69, 38, 94],
        [83, 63, 89, 39, 14]],

       [[26, 70,  3,  5, 89],
        [94, 49, 35, 43, 99],
        [82, 36, 62, 78, 37],
        [90, 73,  9, 38, 40],
        [60, 68,  8,  2, 53]]])

In [12]:
convToOrder_vect = np.vectorize( convToOrder)

In [13]:
boards_order = convToOrder_vect(boards_np)

In [14]:
boards_order

array([[[88, 14, 11,  5, 51],
        [33, 48, 28, 82, 79],
        [61,  2, 77, 98, 10],
        [86, 85, 35, 29, 73],
        [91, 38, 96,  0, 56]],

       [[29, 11, 14,  3, 68],
        [91, 60, 25, 46, 59],
        [17, 36, 35, 57, 99],
        [87, 85, 88, 18, 16],
        [48, 50,  5, 58, 12]],

       [[83, 75, 82, 46, 69],
        [13, 49, 37, 64, 21],
        [41, 20, 11, 57, 12],
        [86, 61, 70, 94, 27],
        [60, 77,  9, 30,  3]],

       ...,

       [[72, 89, 22, 25, 39],
        [ 8, 54, 41, 11, 63],
        [74, 73, 98, 78, 64],
        [96, 70,  7,  9, 32],
        [49, 43, 42, 21, 52]],

       [[ 2, 13, 91, 97,  6],
        [93, 65, 17, 19, 40],
        [63, 18, 27, 14, 20],
        [ 1, 71, 96, 11, 67],
        [22, 12, 81, 52,  0]],

       [[75, 64,  4, 72, 81],
        [67, 39, 90, 13, 74],
        [78, 83, 14, 91, 65],
        [98, 62, 41, 11, 47],
        [28, 16,  3, 27, 25]]])

In [15]:
#For each board get the maximum along rows, and max along columns

b_vmin = []

for b in boards_order:
    print(b)
    b_min_a0 = np.amax( b, axis=0 )
    b_min_a1 = np.amax( b, axis=1 )
    b_vmin.append( np.min( [ b_min_a0, b_min_a1]) )


[[88 14 11  5 51]
 [33 48 28 82 79]
 [61  2 77 98 10]
 [86 85 35 29 73]
 [91 38 96  0 56]]
[[29 11 14  3 68]
 [91 60 25 46 59]
 [17 36 35 57 99]
 [87 85 88 18 16]
 [48 50  5 58 12]]
[[83 75 82 46 69]
 [13 49 37 64 21]
 [41 20 11 57 12]
 [86 61 70 94 27]
 [60 77  9 30  3]]
[[46 91  4 26 61]
 [63 59 32 54 11]
 [24 51 10 38 78]
 [36 16 81 70 66]
 [ 8 87 47 14  7]]
[[16 11 13 27 53]
 [82 66 39 84 80]
 [87 24 62 49  1]
 [38 10 28 52  9]
 [ 4 76 90 67 92]]
[[54 34 27  1 17]
 [96  4 87 42 31]
 [14 47 65 68 13]
 [69 15 64 83 62]
 [63 32 70 11 95]]
[[74 83  5 22 96]
 [44 57 33 49 86]
 [87 55 78 48  1]
 [36 30 61 15 27]
 [52 77 94 25 88]]
[[ 8 37 84 32 96]
 [81 41 29 36 85]
 [ 9 91 78 54 24]
 [ 1 51 65 19 23]
 [92 44 33 46 79]]
[[39 33 60 22 23]
 [18  7  2 45 85]
 [79  1 56 91 15]
 [73 69 10  4 77]
 [43  6 49 55 27]]
[[63 77 30 66 28]
 [49 76 85 15 99]
 [14 82 33 17 91]
 [52 88 95 32 37]
 [48 44 47 93 61]]
[[78 43 62 36 38]
 [21 61 24 14 72]
 [29 99 25 82 39]
 [11 73 70 96 16]
 [90 95 66 45 92]]

In [16]:
b_vmin

[79,
 58,
 57,
 63,
 52,
 47,
 49,
 54,
 55,
 63,
 70,
 74,
 59,
 55,
 56,
 46,
 61,
 25,
 64,
 43,
 70,
 75,
 50,
 42,
 77,
 44,
 56,
 40,
 61,
 56,
 53,
 81,
 61,
 75,
 71,
 64,
 59,
 59,
 61,
 53,
 20,
 80,
 48,
 38,
 59,
 74,
 65,
 68,
 43,
 28,
 60,
 47,
 55,
 59,
 58,
 54,
 63,
 79,
 72,
 41,
 61,
 64,
 83,
 56,
 49,
 53,
 67,
 71,
 64,
 77,
 66,
 65,
 41,
 75,
 35,
 60,
 68,
 56,
 66,
 67,
 44,
 34,
 34,
 45,
 65,
 64,
 58,
 60,
 62,
 50,
 60,
 60,
 63,
 46,
 68,
 56,
 75,
 52,
 63,
 28]

In [17]:
#Get the loosing board
board_min = np.argmax(b_vmin)
board_min

62

In [18]:
v_order_min  = b_vmin[board_min]
v_order_min

83

In [19]:
board_win = boards[board_min]

In [20]:
board_win

[[91, 51, 90, 93, 6],
 [77, 35, 13, 50, 17],
 [89, 75, 57, 39, 36],
 [92, 64, 56, 20, 78],
 [12, 80, 34, 69, 9]]

In [21]:
#With this board then get the score
#Mark those numbers in the winning board that were called

In [22]:
called_numbers = np.array(balls)[:v_order_min+1]
called_numbers

array([14, 30, 18,  8,  3, 10, 77,  4, 48, 67, 28, 38, 63, 43, 62, 12, 68,
       88, 54, 32, 17, 21, 83, 64, 97, 53, 24,  2, 60, 96, 86, 23, 20, 93,
       65, 34, 45, 46, 42, 49, 71,  9, 61, 16, 31,  1, 29, 40, 59, 87, 95,
       41, 39, 27,  6, 25, 19, 58, 80, 81, 50, 79, 73, 15, 70, 37, 92, 94,
        7, 55, 85, 98,  5, 84, 99, 26, 66, 57, 82, 75, 22, 89, 74, 36])

In [23]:
lastvalue= balls[v_order_min]
lastvalue

36

In [24]:
def hasBeenCalled(v):
    print(f"v={v}")
    index = np.where(called_numbers == v)
    index = index[0]
    print(f"index={index}")
    ret=0
    if index.size>0:
        ret=1
    return ret

hasBeenCalled_vector = np.vectorize(hasBeenCalled)

In [25]:
boardwin_hasBeenCalled = hasBeenCalled_vector(board_win)

v=91
index=[]
v=91
index=[]
v=51
index=[]
v=90
index=[]
v=93
index=[33]
v=6
index=[54]
v=77
index=[6]
v=35
index=[]
v=13
index=[]
v=50
index=[60]
v=17
index=[20]
v=89
index=[81]
v=75
index=[79]
v=57
index=[77]
v=39
index=[52]
v=36
index=[83]
v=92
index=[66]
v=64
index=[23]
v=56
index=[]
v=20
index=[32]
v=78
index=[]
v=12
index=[15]
v=80
index=[58]
v=34
index=[35]
v=69
index=[]
v=9
index=[41]


In [26]:
boardwin_hasBeenCalled

array([[0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1]])

In [27]:
boardwin_notBeenCalled = -boardwin_hasBeenCalled +1 #inverts

In [28]:
boardwin_notBeenCalled

array([[1, 1, 1, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0]])

In [29]:
sum_notcalled =  np.sum(boardwin_notBeenCalled* board_win)

In [30]:
sum_notcalled

483

In [31]:
score = sum_notcalled * lastvalue
score

17388