In [ ]:
#INPUT_FN = "input_test.txt" # 374

INPUT_FN = "input.txt"

with open(INPUT_FN) as f:
    lines = [l.rstrip() for l in f]

if lines[-1]=='':
    lines=lines[:,-1]

In [2]:
lines

['......#.....#.........................#...........#..........#.....#.......#..............#.................................................',
 '.....................#....................................................................................#........#........#.......#.......',
 '.........................................................#............................#..................................................#..',
 '.........................#.......#..............................#............................#.................#............................',
 '..................#...................................................................................#.....................................',
 '...........................................#....................................#.................................................#.........',
 '...........................................................#..........#..........................#..............................

Use numpy and convert galaxies to numbers

In [3]:
nrows = len(lines)
ncols = len(lines[0])
print(f"{nrows=}, {ncols=}")

nrows=140, ncols=140


In [4]:
import numpy as np
univ = np.zeros((nrows, ncols), dtype=np.uint32)
gcount=1
for irow,line in enumerate(lines):
    for icol,s in enumerate(line):
        if s=='#':
            univ[irow,icol]=gcount
            gcount+=1

In [5]:
univ

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,  16,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0, 445,   0, ...,   0,   0,   0]], dtype=uint32)

Find empty rows and cols and expands

In [6]:
empty_rows = np.any(univ>0, axis=1)
empty_rows

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

Expands where it has no galaxies

In [7]:
irows_no_galaxies = np.nonzero(empty_rows==False)[0]
irows_no_galaxies

array([16, 31, 38, 43, 52, 58, 62, 63, 71, 77, 79, 80, 93], dtype=int64)

In [8]:
expand_row = np.zeros((univ.shape[1]), dtype=np.uint32)
expand_row

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [9]:
univ_row_exp = np.insert(univ, irows_no_galaxies, expand_row, axis=0)

In [10]:
univ_row_exp

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,  16,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0, 445,   0, ...,   0,   0,   0]], dtype=uint32)

column-wise

In [11]:
empty_cols = np.any(univ_row_exp>0, axis=0)
empty_cols

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [12]:
icols_no_galaxies = np.nonzero(empty_cols==False)[0]
icols_no_galaxies

array([51, 63, 71, 78, 82], dtype=int64)

In [13]:
expand_col = np.zeros((univ_row_exp.shape[0],1), dtype=np.uint32)
expand_col

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [14]:
univ_row_exp.shape

(153, 140)

In [15]:
univ_row_col_exp = np.insert(univ_row_exp, icols_no_galaxies, expand_col, axis=1)

In [16]:
univ_row_col_exp

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,  16,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0, 445,   0, ...,   0,   0,   0]], dtype=uint32)

OK.

Now we need to get manhatan distances between combinations

In [17]:
n_galaxies = univ_row_col_exp.max()
n_galaxies

450

In [18]:
# Try between galaxy 1 and 7

g1 = np.where(univ_row_col_exp==1)
g1 = (g1[0][0], g1[1][0])
g1

(0, 6)

In [ ]:
def get_coords_of_galaxy(N):
    gN = np.where(univ_row_col_exp==N)
    res = (gN[0][0], gN[1][0])
    return res

In [ ]:
get_coords_of_galaxy(7)

(0, 78)

In [21]:
def manh_dist(c1, c2):
    dist = abs(c1[0]-c2[0]) + abs(c1[1]-c2[1])
    return dist

In [ ]:
manh_dist( get_coords_of_galaxy(1), get_coords_of_galaxy(7))

72

In [ ]:
manh_dist( get_coords_of_galaxy(3), get_coords_of_galaxy(6))

31

Do all combinations of galaxies

In [24]:
import itertools

g_combs = list(itertools.combinations(range(1,n_galaxies+1),2))
g_combs

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 28),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (1, 34),
 (1, 35),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 39),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (1, 50),
 (1, 51),
 (1, 52),
 (1, 53),
 (1, 54),
 (1, 55),
 (1, 56),
 (1, 57),
 (1, 58),
 (1, 59),
 (1, 60),
 (1, 61),
 (1, 62),
 (1, 63),
 (1, 64),
 (1, 65),
 (1, 66),
 (1, 67),
 (1, 68),
 (1, 69),
 (1, 70),
 (1, 71),
 (1, 72),
 (1, 73),
 (1, 74),
 (1, 75),
 (1, 76),
 (1, 77),
 (1, 78),
 (1, 79),
 (1, 80),
 (1, 81),
 (1, 82),
 (1, 83),
 (1, 84),
 (1, 85),
 (1, 86),
 (1, 87),
 (1, 88),
 (1, 89),
 (1, 90),
 (1, 91),
 (1, 92),
 (1, 93),
 (1, 94),
 (1, 95),
 (1, 96),
 (1, 97),
 (1, 98),
 (1, 99),
 (1, 100),
 (1, 101),
 (1, 1

In [ ]:
dist_sum = 0

for comb1 in g_combs:
    dist_sum+= manh_dist( get_coords_of_galaxy(comb1[0]), get_coords_of_galaxy(comb1[1]))
dist_sum

10494813