In [1]:
import numpy as np
import re

In [2]:
#with open("input_test.txt", 'r') as f0:
with open("input.txt", 'r') as f0:
    lines0= f0.readlines()

lines = [l0.strip() for l0 in lines0]

In [3]:
lines

['..........................380.......................143............................108.............630...........425........................',
 '....*585..30....217*616..........$...................../....$.................447...........381..................+..........973.............',
 '.210......*...............639...541..-........830*...........912..........743*.......................828..671........+......*...............',
 '.......760....$..............*........737.*.......949..568.......................=........628.85........&.#..........87...535.....794.......',
 '....#......616..........373.999..392......853..........&.........666.......*.....365.............807............@....................*......',
 '.680................800*..............684................329....*.......960.186........725........*......&.....631.....700*818..............',
 '............-402...........%.........@.........576.............956................../.....*....237....490.......................

In [4]:
# Convert lines to array

dimx =  len(lines[0])
dimy = len(lines)

digits = np.zeros((dimy,dimx), dtype=bool)
symbols = np.zeros_like(digits, dtype=bool)

for iy,l0 in enumerate(lines):
    for ix,s0 in enumerate(l0):
        if s0.isdigit():
            digits[iy,ix]=True
        elif s0!='.':
            # is symbol then
            symbols[iy,ix]=True

In [5]:
digits

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [6]:
symbols

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [7]:
#Iterate to mark the part numbers
# Use convolutions
from scipy import ndimage
conv_kern = np.ones((3,3), dtype=np.uint8)

symbols_i = np.array(symbols).astype(np.uint8) # make a copy

symbols_conv= ndimage.convolve(symbols_i, conv_kern, mode='constant', cval=0)

symbols_conv_bool = symbols_conv>0

digits_to_account = symbols_conv_bool *  digits #Boolean and

In [8]:
#Iterate to mark the part numbers
# Use convolutions
from scipy import ndimage
conv_kern = np.ones((3,3), dtype=np.uint8)

symbols_i = np.array(symbols).astype(np.uint8) # make a copy

ndigits=0
i=0
while True:
    print(i)
    symbols_conv= ndimage.convolve(symbols_i, conv_kern, mode='constant', cval=0)
    symbols_conv_bool = symbols_conv>0
    symbols_i = symbols_conv_bool *  digits #Boolean and
    ndigits1 = np.sum(symbols_i)
    if ndigits1<= ndigits:
        break
    ndigits = ndigits1
    i+=1

0
1
2
3


In [9]:
symbols_i

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [10]:
#Get the values

values=[]

for iy,l0 in enumerate(lines):
    filt_line= list(l0)
    for ix,s0 in enumerate(l0):
        if not symbols_i[iy,ix]:
            filt_line[ix]=' '
    filt_line="".join(filt_line)
    print(f"iy:{iy} , filt_line:{filt_line}")

    r0 = re.findall("[0-9]+",filt_line)

    for s in r0:
        values.append(int(s))

iy:0 , filt_line:                                                    143                                                          425                        
iy:1 , filt_line:     585  30    217 616                                                       447                                           973             
iy:2 , filt_line: 210                      639   541           830            912          743                        828  671                               
iy:3 , filt_line:       760                            737         949  568                                                           87   535     794       
iy:4 , filt_line:           616          373 999           853                    666             365             807                                        
iy:5 , filt_line: 680                800               684                               960 186        725                     631     700 818              
iy:6 , filt_line:             402                   

In [11]:
values

[143,
 425,
 585,
 30,
 217,
 616,
 447,
 973,
 210,
 639,
 541,
 830,
 912,
 743,
 828,
 671,
 760,
 737,
 949,
 568,
 87,
 535,
 794,
 616,
 373,
 999,
 853,
 666,
 365,
 807,
 680,
 800,
 684,
 960,
 186,
 725,
 631,
 700,
 818,
 402,
 956,
 237,
 490,
 998,
 624,
 600,
 283,
 906,
 301,
 495,
 917,
 165,
 193,
 977,
 610,
 489,
 795,
 545,
 915,
 641,
 123,
 113,
 643,
 117,
 483,
 961,
 984,
 878,
 277,
 80,
 802,
 591,
 228,
 848,
 810,
 740,
 902,
 201,
 993,
 268,
 429,
 582,
 538,
 789,
 941,
 136,
 334,
 508,
 250,
 745,
 77,
 653,
 491,
 192,
 978,
 26,
 957,
 400,
 834,
 85,
 429,
 291,
 690,
 69,
 814,
 276,
 571,
 65,
 765,
 179,
 460,
 577,
 50,
 758,
 52,
 821,
 676,
 227,
 273,
 789,
 288,
 226,
 592,
 943,
 378,
 876,
 497,
 575,
 524,
 353,
 664,
 781,
 108,
 124,
 407,
 272,
 43,
 421,
 708,
 405,
 769,
 432,
 57,
 887,
 637,
 96,
 700,
 573,
 644,
 802,
 798,
 897,
 456,
 130,
 182,
 420,
 369,
 121,
 916,
 637,
 816,
 911,
 97,
 990,
 557,
 355,
 578,
 764,
 872,


In [12]:
np.sum(values)

526404

test: 4361, OK