In [1]:
import numpy as np

In [2]:
#file_input = 'input_test.txt'
file_input = 'input.txt'

In [3]:
with open(file_input) as f:
    filestr = f.read()

Collect information from file

In [4]:
blupr_str = filestr.split("Blueprint")
blupr_str

['',
 ' 1: Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 18 clay. Each geode robot costs 4 ore and 9 obsidian.\n',
 ' 2: Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 10 clay. Each geode robot costs 2 ore and 7 obsidian.\n',
 ' 3: Each ore robot costs 4 ore. Each clay robot costs 3 ore. Each obsidian robot costs 4 ore and 15 clay. Each geode robot costs 3 ore and 12 obsidian.\n',
 ' 4: Each ore robot costs 3 ore. Each clay robot costs 4 ore. Each obsidian robot costs 3 ore and 10 clay. Each geode robot costs 2 ore and 7 obsidian.\n',
 ' 5: Each ore robot costs 4 ore. Each clay robot costs 3 ore. Each obsidian robot costs 2 ore and 13 clay. Each geode robot costs 2 ore and 10 obsidian.\n',
 ' 6: Each ore robot costs 3 ore. Each clay robot costs 3 ore. Each obsidian robot costs 3 ore and 9 clay. Each geode robot costs 2 ore and 10 obsidian.\n',
 ' 7: Each ore robot costs 4 ore. Each clay robot c

In [5]:
ores = ['geode', 'obsidian', 'clay','ore']

TODO: Modify so that the blueprints are simply arrays at order of ores

In [6]:
ores_dict = {'geode':0, 'obsidian':1, 'clay':2,'ore':3}
#ores_dict_inv = {0:'geode'}

In [7]:
blueprints={}

for b0 in blupr_str:

    if b0!='':
        #Initialise blueprint
        blueprint = [0,0,0,0]
        # for o0 in ores:
        #     blueprint[o0]={}
        
        b0_split = b0.split(':')
        print(f"b0_split:{b0_split}")
        bp_number = int(b0_split[0])
        bp_key = bp_number
        bp_value={}

        b_rest = b0_split[1]

        b_details_split = b_rest.split('.')
        print(f"b_details_split:{b_details_split}")

        for b1 in b_details_split:
            b1=b1.strip('\n')
            if 'costs' in b1:
                # #Initialise costs
                # robot_costs = {}
                # for o0 in ores:
                #     robot_costs[o0]=0

                b2=b1.split('costs')
                print(f"b2:{b2}")

                brobot = ''
                irobot = 0
                b2_robot = b2[0]
                if 'ore' in b2_robot:
                    brobot = 'ore'
                    irobot=3
                if 'clay' in b2_robot:
                    brobot = 'clay'
                    irobot=2
                if 'obsidian' in b2_robot:
                    brobot = 'obsidian'
                    irobot=1
                if 'geode' in b2_robot:
                    brobot = 'geode'
                    irobot=0
                
                b2_costs = b2[1]

                b2_costs_split = b2_costs.split('and')
                print(f"b2_costs_split:{b2_costs_split}")

                robot_costs = np.zeros((4),dtype=np.int32)
                for b3 in b2_costs_split:

                    cost_key=''
                    cost_value=0

                    b3_split = b3.split(' ')
                    print(f"b3_split:{b3_split}")
                    for b4 in b3_split:
                        if b4!='':
                            if b4.isnumeric():
                                cost_value=int(b4)
                            else:
                                if 'ore' in b4:
                                    cost_key = 'ore'
                                if 'clay' in b4:
                                    cost_key = 'clay'
                                if 'obsidian' in b4:
                                    cost_key = 'obsidian'
                                if 'geode' in b4: #This may not be necessary
                                    cost_key = 'geode'
                    if cost_key!='':
                        robot_costs[ores_dict[cost_key]] = cost_value


                #blueprint[]= robot_costs
                blueprint[irobot] = robot_costs
        
            blueprints[bp_number] = blueprint

b0_split:[' 1', ' Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 18 clay. Each geode robot costs 4 ore and 9 obsidian.\n']
b_details_split:[' Each ore robot costs 4 ore', ' Each clay robot costs 4 ore', ' Each obsidian robot costs 4 ore and 18 clay', ' Each geode robot costs 4 ore and 9 obsidian', '\n']
b2:[' Each ore robot ', ' 4 ore']
b2_costs_split:[' 4 ore']
b3_split:['', '4', 'ore']
b2:[' Each clay robot ', ' 4 ore']
b2_costs_split:[' 4 ore']
b3_split:['', '4', 'ore']
b2:[' Each obsidian robot ', ' 4 ore and 18 clay']
b2_costs_split:[' 4 ore ', ' 18 clay']
b3_split:['', '4', 'ore', '']
b3_split:['', '18', 'clay']
b2:[' Each geode robot ', ' 4 ore and 9 obsidian']
b2_costs_split:[' 4 ore ', ' 9 obsidian']
b3_split:['', '4', 'ore', '']
b3_split:['', '9', 'obsidian']
b0_split:[' 2', ' Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 10 clay. Each geode robot costs 2 ore and 7 obsidian.\n']
b_det

In [8]:
blueprints

{1: [array([0, 9, 0, 4]),
  array([ 0,  0, 18,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 2: [array([0, 7, 0, 2]),
  array([ 0,  0, 10,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 3: [array([ 0, 12,  0,  3]),
  array([ 0,  0, 15,  4]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 4: [array([0, 7, 0, 2]),
  array([ 0,  0, 10,  3]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 3])],
 5: [array([ 0, 10,  0,  2]),
  array([ 0,  0, 13,  2]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 6: [array([ 0, 10,  0,  2]),
  array([0, 0, 9, 3]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 3])],
 7: [array([0, 7, 0, 2]),
  array([ 0,  0, 11,  2]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 8: [array([ 0, 19,  0,  2]),
  array([ 0,  0, 18,  3]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 2])],
 9: [array([ 0, 10,  0,  2]),
  array([0, 0, 5, 2]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 10: [array([0, 7, 0, 4]),
  array([ 0,  0, 11,  3]),
  array([0, 0, 0, 3]),
  array([0,

# Engine 1

Do for each minute.

* Create a list of how to spend the existing ores (remember that one option is not to spend anything)
* Decide from list how to spend
  * Collect ores/clay/obsidian/geodes
  * Update list of robots from spenditure list
  * go to next minute. but if current minute of 24, count the number of geodes created and ends (return max value)
* Get max geode from the list and return

First minute starts with no materials and one ore collecting robot

In [ ]:
#Assume materials_count and robots count is is a numpy array with 4 values
# with the order 'geode', 'obsidian', 'clay','ore'

#robot_buy_order = ['geode', 'obsidian', 'clay','ore', None]
robot_buy_order_i = [0, 1, 2,3, None]
maxgeode_global = 0

already_calculated={}

def maxAtMinute(blueprint, robots_count, materials_count, minute, maxminutes):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    maxgeodes = 0 #default
    
    global maxgeode_global
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    #for robot_type in robot_buy_order:
    for robot_type in robot_buy_order_i:
        #print(f"Checking if can buy {robot_type}")

        maxgeode0=0
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()

        if not robot_type is None:
            #Check if materials are enough to buy the robot
            robot_costs = blueprint[robot_type]

            #Test materials that will be left if we buy the robot
            materials_count1 -= robot_costs
            
            #If all the materials count is positive then we can buy the robot

        #print(f"If we could use this {robot_type} robot, the materials left would be {materials_count1}")
        bCanBuy=True
        if np.min(materials_count1)<0:
            #print(f"Cannot buy this robot: {robot_type}")
            pass
        else:
            #print("Can buy")
            #Go to next day
            #Update materials with robot collection values
            #Each robot collects one of each material
            materials_count1+= robots_count

            #print(f"Robots collect materials, so we are left with {materials_count1}")
            
            if not robot_type is None:
                #robots_count1[ores_dict[robot_type]]+=1
                robots_count1[robot_type]+=1
                
                #print(f"New robot acquired, robot_count1 is now {robots_count1}")

            minute1 = minute+1
            #Check if reached maximum number of minutes
            if minute1>maxminutes:
                return materials_count1[0]

            #print(f"Entering {minute1} mins...")
            maxgeode0 = maxAtMinute(blueprint,robots_count1,materials_count1,minute1, maxminutes)
            #print(f"{minute} mins, maxgeode0: {maxgeode0}")

            maxgeodes = max(maxgeodes, maxgeode0)
            
            if maxgeodes>maxgeode_global:
                print(f"Min {minute} min, new geode max: {maxgeodes}")
                maxgeode_global=maxgeodes
            
        
    #print(f"{minute} mins. Checked all options, maxgeodes collected are {maxgeodes}")
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes
    
    return maxgeodes

In [ ]:
robots_count_init = np.array([0,0,0,1])
materials_count_init = np.array([0,0,0,0])
maxgeode_global=0
maxAtMinute(blueprints[1], robots_count_init, materials_count_init, 1, 24)

This takes too long

Try a different optmizer.


# New Optimizer


Check for how to optimize the production of geode robots

Look at requirements. Compare with materials available, subtract req - current_materials. Any value >0 is a material required. Compare with robots. If the number of robots for that is zero then focus in the production of that robot, by replacing 'adding' the robot requiremens to the required.

Compare again mat_available - required, and compare with robots_available again. Again, if there is a material required and no robot to make, then replace robot with materials

If all robots are there for all materials. Divide the materials required with the number of robots. The highest of the values should indicate the robot that should be prioritised for production.

In [ ]:
blueprints[1]

In [ ]:
#This is not working well
def getPriorityRobotPurchase(blueprint, robots_count, materials_count):
    #required is geode = [1,0,0,0]

    production_materials_needed = blueprint['geode']
    print(f"production_materials_needed:{production_materials_needed}, materials_count:{materials_count}")
    required_mat = production_materials_needed - materials_count

    if np.all( required_mat<=0):
        print("Requirements to buy geode already met")
        return 0
    else:
        while True:
            
            print(f"required_mat:{required_mat}")
            
            robots_needed = np.logical_and( required_mat>0 , robots_count==0 )
            print(f"robots_needed:{robots_needed}")

            if np.any(robots_needed):
                #In case there are no robots to produce some of the materials needed
                # then figure out a way to urgently produce these robots
                #TODO
                for i0, value in enumerate(robots_needed):
                    if value:
                        #Sum to the required materials
                        #get key from value in dictionary
                        robot_type= [i for i in ores_dict if ores_dict[i]==i0][0]
                        #print(f"robot_index:{robot_type}")
                        required_mat += blueprint[robot_type]

                        required_mat[i0]=0 #Reset the robots needed
            else:
                break #exit the while loop
        
        #Where there are required materials, divide by the number of robots
        div_res = np.zeros((4))
        np.divide(required_mat, robots_count, where= (required_mat>0) , out=div_res)
        
        #print(f"div_res:{div_res}")
        #Get the maximum in required_mat
        
        max_i = np.argmax(div_res)

        if max_i is None:
            max_i = 2 #Default to buy clay robot if possible

        return max_i

In [ ]:
#Test
robots_count_init = np.array([0,0,0,1])
materials_count_init = np.array([0,0,0,0])
getPriorityRobotPurchase(blueprints[2], robots_count_init, materials_count_init)


In [ ]:
#Test min17 to 18
robots_count_init = np.array([0,2,4,1])
materials_count_init = np.array([0,8,13,3])
getPriorityRobotPurchase(blueprints[1], robots_count_init, materials_count_init)

In [ ]:
#Test min14 to 15
robots_count_init = np.array([0,1,4,1])
materials_count_init = np.array([0,3,15,3])
getPriorityRobotPurchase(blueprints[1], robots_count_init, materials_count_init)

In [ ]:
#Test min 2 to 3
robots_count_init = np.array([0,0,0,1])
materials_count_init = np.array([0,0,0,2])
getPriorityRobotPurchase(blueprints[1], robots_count_init, materials_count_init)


In [ ]:
#Test other
robots_count_init = np.array([0,0,0,8])
materials_count_init = np.array([0,0,0,7])
getPriorityRobotPurchase(blueprints[1], robots_count_init, materials_count_init)

In [ ]:

#Assume materials_count and robots count is is a numpy array with 4 values
# with the order 'geode', 'obsidian', 'clay','ore'

robot_buy_order = ['geode', 'obsidian', 'clay','ore', None]
maxgeode_global = 0

def maxAtMinute1(blueprint, robots_count, materials_count, minute, maxminutes):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    
    maxgeodes = 0 #default
    
    global maxgeode_global
    
    irobot = getPriorityRobotPurchase(blueprint, robots_count, materials_count)

    #Get robot type from dictionary of ores
    robot_type= [i for i in ores_dict if ores_dict[i]==irobot][0]
    #print(f"Suggested next robot purchase: {robot_type}")

    #maxgeode0=0
    materials_count1 = materials_count.copy() #Hopefully, np array copy properly
    robots_count1 = robots_count.copy()

    #Check if materials are enough to buy the robot
    robot_costs = blueprint[robot_type]

    #Test materials that will be left if we buy the robot
    materials_count1 -= robot_costs
    
    #If all the materials count is positive then we can buy the robot

    #print(f"If we could use this {robot_type} robot, the materials left would be {materials_count1}")
    bCanBuy=True
    if np.min(materials_count1)<0:
        #print(f"Cannot buy this robot {robot_type}")
        robot_type=None
        #Go to next minute and revert materials_count
        materials_count1=materials_count.copy()
    else:
        #print("Can buy")

    #Go to next day
    #Update materials with robot collection values
    #Each robot collects one of each material
    
    materials_count1+= robots_count

    #print(f"Robots collect materials, leading to {materials_count1}")
    
    if not robot_type is None:
        robots_count1[ores_dict[robot_type]]+=1
        #print(f"New robot acquired, robot_count1 is now {robots_count1}")

    minute1 = minute+1
    #Check if reached maximum number of minutes
    if minute1>maxminutes:
        return materials_count1[0]

    #print(f"Entering {minute1} mins...")
    maxgeode = maxAtMinute1(blueprint,robots_count1,materials_count1,minute1, maxminutes)
    #print(f"{minute} mins, maxgeode0: {maxgeode0}")

    #maxgeodes = max(maxgeodes, maxgeode0)
    
    if maxgeodes>maxgeode_global:
        print(f"Min {minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
            
        
    #print(f"{minute} mins. Checked all options, maxgeodes collected are {maxgeodes}")

    return maxgeodes

In [ ]:
robots_count_init = np.array([0,0,0,1])
materials_count_init = np.array([0,0,0,0])
maxgeode_global=0
maxAtMinute1(blueprints[1], robots_count_init, materials_count_init, 1, 24)

# Optimizer 2

In [9]:
#This is not working well
def getOptionsNext(blueprint, robots_count, materials_count):
    #Returns a index of robot to buy or None for not buying

    #Check which robots I can buy with the materials I have
    canIBuy=np.zeros((4),dtype=bool)
    for ibp, bpitem in enumerate(blueprint):
        canIBuy[ibp] = np.all( (materials_count-bpitem)>=0)
    #print(f"canIBuy: {canIBuy}")

    buylist = list( np.nonzero(canIBuy)[0] )
    buylist.append(None)
    #print(f"buylist:{buylist}")

    return buylist


In [10]:
maxgeode_global = 0

In [11]:
def maxAtMinute2(blueprint, robots_count, materials_count, minute, maxminutes):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    global maxgeode_global
    global already_calculated
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    #Check if there is any chance to get a better result. Number of geode robots and geode materials
    minleft = maxminutes-minute
    maxgeodes_possible = materials_count[0] +1+ (2*(robots_count[0]+1)+minleft)*(minleft+1)/2
    if maxgeodes_possible<maxgeode_global:
        return 0 #Get out if it is not possible to do better

    maxgeodes = 0 #default
    
    
    buylist = getOptionsNext(blueprint, robots_count, materials_count)
    #print(f"buylist:{buylist}")
    
    maxgeode0=0

    for buyrobot0 in buylist:
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()
        #print(f"Buying robot {buyrobot0}.")

        if not buyrobot0 is None:
            #Test materials that will be left if we buy the robot
            materials_count1 -= blueprint[buyrobot0]
    
            #print(f"After buying this robot the materials left is {materials_count1}")

        #Update materials based in the number of robots
        materials_count1+= robots_count
        #print(f"Robots collect materials, leading to {materials_count1}")
    
        #Update robot count at end of minute if there was a purchase
        if not buyrobot0 is None:
            robots_count1[buyrobot0]+=1
            #print(f"New robot acquired, robot_count1 is now {robots_count1}")

        minute1 = minute+1
        #Check if reached maximum number of minutes
        if minute1>maxminutes:
            return materials_count1[0]

        #print(f"Entering {minute1} mins...")
        maxgeode0 = maxAtMinute2(blueprint,robots_count1,materials_count1,minute1, maxminutes)
        #print(f"{minute} mins, maxgeode0: {maxgeode0}")

        maxgeodes= max(maxgeodes, maxgeode0)

    if maxgeodes>maxgeode_global:
        #print(f"{minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
        
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes

    return maxgeodes

In [19]:
def maxAtMinute2_deep(blueprint, robots_count, materials_count, minute, maxminutes):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    global maxgeode_global
    global already_calculated
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    # #Check if there is any chance to get a better result. Number of geode robots and geode materials
    # minleft = maxminutes-minute
    # maxgeodes_possible = materials_count[0] + (2*robots_count[0]+minleft)*(minleft+1)/2
    # if maxgeodes_possible<maxgeode_global:
    #     return 0 #Get out if it is not possible to do better

    maxgeodes = 0 #default
    
    
    buylist = getOptionsNext(blueprint, robots_count, materials_count)
    #print(f"buylist:{buylist}")
    
    maxgeode0=0

    for buyrobot0 in buylist:
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()
        #print(f"Buying robot {buyrobot0}.")

        if not buyrobot0 is None:
            #Test materials that will be left if we buy the robot
            materials_count1 -= blueprint[buyrobot0]
    
            #print(f"After buying this robot the materials left is {materials_count1}")

        #Update materials based in the number of robots
        materials_count1+= robots_count
        #print(f"Robots collect materials, leading to {materials_count1}")
    
        #Update robot count at end of minute if there was a purchase
        if not buyrobot0 is None:
            robots_count1[buyrobot0]+=1
            #print(f"New robot acquired, robot_count1 is now {robots_count1}")

        minute1 = minute+1
        #Check if reached maximum number of minutes
        if minute1>maxminutes:
            return materials_count1[0]

        #print(f"Entering {minute1} mins...")
        maxgeode0 = maxAtMinute2_deep(blueprint,robots_count1,materials_count1,minute1, maxminutes)
        #print(f"{minute} mins, maxgeode0: {maxgeode0}")

        maxgeodes= max(maxgeodes, maxgeode0)

    if maxgeodes>maxgeode_global:
        #print(f"{minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
        
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes

    return maxgeodes

In [20]:
def getMaxGeodesForBlueprint(blueprint):
    global already_calculated

    robots_count_init = np.array([0,0,0,1])
    materials_count_init = np.array([0,0,0,0])
    maxgeode_global=0
    already_calculated={}
    return maxAtMinute2(blueprint, robots_count_init, materials_count_init, 1, 24)

In [21]:
def getMaxGeodesForBlueprint_deep(blueprint):
    global already_calculated
    
    robots_count_init = np.array([0,0,0,1])
    materials_count_init = np.array([0,0,0,0])
    maxgeode_global=0
    already_calculated={}
    return maxAtMinute2_deep(blueprint, robots_count_init, materials_count_init, 1, 24)

In [22]:
#Compare results of two different functions
bp = blueprints[1]
print(getMaxGeodesForBlueprint(bp))
print(getMaxGeodesForBlueprint_deep(bp))

0
0


In [23]:
#Compare results of two different functions
bp = blueprints[2]
print(getMaxGeodesForBlueprint(bp))
print(getMaxGeodesForBlueprint_deep(bp))

4
4


In [24]:
#Compare results of two different functions
bp = blueprints[3]
print(getMaxGeodesForBlueprint(bp))
print(getMaxGeodesForBlueprint_deep(bp))

0
1


In [25]:
#Compare results of two different functions
bp = blueprints[5]
print(getMaxGeodesForBlueprint(bp))
print(getMaxGeodesForBlueprint_deep(bp))

3
3


No result!!

In [26]:
getMaxGeodesForBlueprint_deep(blueprints[5])

3

In [27]:
print(getMaxGeodesForBlueprint(blueprints[5]))

3


In [32]:
#test
getMaxGeodesForBlueprint(blueprints[2])

KeyboardInterrupt: 

In [ ]:
getMaxGeodesForBlueprint_deep(blueprints[2])

KeyboardInterrupt: 

It is giving the right answer now. And at a reasonable time

# Calculate for all blueprints

In [ ]:
#Test
getMaxGeodesForBluepprint(blueprints[1])

In [ ]:
getMaxGeodesForBluepprint(blueprints[2])

OK

In [20]:
bp_scores = []
for bp_number, bp in blueprints.items():
    print(f"bp_number:{bp_number}, blueprint:{bp}")
    bpmax= getMaxGeodesForBluepprint(bp)
    score = bp_number*bpmax
    print(f"bpmax:{bpmax}, score:{score}")
    bp_scores.append(score)

bp_number:1, blueprint:[array([0, 9, 0, 4]), array([ 0,  0, 18,  4]), array([0, 0, 0, 4]), array([0, 0, 0, 4])]
bpmax:0, score:0
bp_number:2, blueprint:[array([0, 7, 0, 2]), array([ 0,  0, 10,  4]), array([0, 0, 0, 4]), array([0, 0, 0, 4])]
bpmax:4, score:8
bp_number:3, blueprint:[array([ 0, 12,  0,  3]), array([ 0,  0, 15,  4]), array([0, 0, 0, 3]), array([0, 0, 0, 4])]
bpmax:1, score:3
bp_number:4, blueprint:[array([0, 7, 0, 2]), array([ 0,  0, 10,  3]), array([0, 0, 0, 4]), array([0, 0, 0, 3])]
bpmax:7, score:28
bp_number:5, blueprint:[array([ 0, 10,  0,  2]), array([ 0,  0, 13,  2]), array([0, 0, 0, 3]), array([0, 0, 0, 4])]
bpmax:3, score:15
bp_number:6, blueprint:[array([ 0, 10,  0,  2]), array([0, 0, 9, 3]), array([0, 0, 0, 3]), array([0, 0, 0, 3])]


KeyboardInterrupt: 

In [15]:
answer = np.sum( np.array(bp_scores))
answer

213 is not the answer