In [1]:
import numpy as np

In [2]:
#file_input = 'input_test_extended.txt'

file_input = 'input.txt'

In [3]:
with open(file_input) as f:
    filestr = f.read()

Collect information from file

In [4]:
blupr_str = filestr.split("Blueprint")

In [5]:
ores = ['geode', 'obsidian', 'clay','ore']

In [6]:
ores_dict = {'geode':0, 'obsidian':1, 'clay':2,'ore':3}
#ores_dict_inv = {0:'geode'}

In [7]:
blueprints={}

for b0 in blupr_str:

    if b0!='':
        #Initialise blueprint
        blueprint = [0,0,0,0]
        # for o0 in ores:
        #     blueprint[o0]={}
        
        b0_split = b0.split(':')
        #print(f"b0_split:{b0_split}")
        bp_number = int(b0_split[0])
        bp_key = bp_number
        bp_value={}

        b_rest = b0_split[1]

        b_details_split = b_rest.split('.')
        #print(f"b_details_split:{b_details_split}")

        for b1 in b_details_split:
            b1=b1.strip('\n')
            if 'costs' in b1:
                # #Initialise costs
                # robot_costs = {}
                # for o0 in ores:
                #     robot_costs[o0]=0

                b2=b1.split('costs')
                #print(f"b2:{b2}")

                brobot = ''
                irobot = 0
                b2_robot = b2[0]
                if 'ore' in b2_robot:
                    brobot = 'ore'
                    irobot=3
                if 'clay' in b2_robot:
                    brobot = 'clay'
                    irobot=2
                if 'obsidian' in b2_robot:
                    brobot = 'obsidian'
                    irobot=1
                if 'geode' in b2_robot:
                    brobot = 'geode'
                    irobot=0
                
                b2_costs = b2[1]

                b2_costs_split = b2_costs.split('and')
                #print(f"b2_costs_split:{b2_costs_split}")

                robot_costs = np.zeros((4),dtype=np.int32)
                for b3 in b2_costs_split:

                    cost_key=''
                    cost_value=0

                    b3_split = b3.split(' ')
                    #print(f"b3_split:{b3_split}")
                    for b4 in b3_split:
                        if b4!='':
                            if b4.isnumeric():
                                cost_value=int(b4)
                            else:
                                if 'ore' in b4:
                                    cost_key = 'ore'
                                if 'clay' in b4:
                                    cost_key = 'clay'
                                if 'obsidian' in b4:
                                    cost_key = 'obsidian'
                                if 'geode' in b4: #This may not be necessary
                                    cost_key = 'geode'
                    if cost_key!='':
                        robot_costs[ores_dict[cost_key]] = cost_value

                #blueprint[]= robot_costs
                blueprint[irobot] = robot_costs
        
            blueprints[bp_number] = blueprint

In [8]:
blueprints

{1: [array([0, 9, 0, 4]),
  array([ 0,  0, 18,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 2: [array([0, 7, 0, 2]),
  array([ 0,  0, 10,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 3: [array([ 0, 12,  0,  3]),
  array([ 0,  0, 15,  4]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 4: [array([0, 7, 0, 2]),
  array([ 0,  0, 10,  3]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 3])],
 5: [array([ 0, 10,  0,  2]),
  array([ 0,  0, 13,  2]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 6: [array([ 0, 10,  0,  2]),
  array([0, 0, 9, 3]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 3])],
 7: [array([0, 7, 0, 2]),
  array([ 0,  0, 11,  2]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 8: [array([ 0, 19,  0,  2]),
  array([ 0,  0, 18,  3]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 2])],
 9: [array([ 0, 10,  0,  2]),
  array([0, 0, 5, 2]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])],
 10: [array([0, 7, 0, 4]),
  array([ 0,  0, 11,  3]),
  array([0, 0, 0, 3]),
  array([0,

For this problem, only the first 3 blueprints are used

In [9]:
blueprints_short ={}
for i in range(1,4):
    blueprints_short[i] = blueprints[i]

In [10]:
blueprints_short

{1: [array([0, 9, 0, 4]),
  array([ 0,  0, 18,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 2: [array([0, 7, 0, 2]),
  array([ 0,  0, 10,  4]),
  array([0, 0, 0, 4]),
  array([0, 0, 0, 4])],
 3: [array([ 0, 12,  0,  3]),
  array([ 0,  0, 15,  4]),
  array([0, 0, 0, 3]),
  array([0, 0, 0, 4])]}

In [11]:
blueprints=blueprints_short

# Optimizer

If the number of collected materials exceeds the maximum cost of respective robot for each materials, avoid buying it. So create a new array here with maximum cost.

In [12]:
def getMaxCost(blueprint):
    #max_cost = np.zeros((4), dtype=np.int8)
    
    costs_np = np.array(blueprint)
    max_cost = np.max(costs_np, axis=0) #Maximum along column
    return max_cost

In [13]:
#Test
getMaxCost(blueprints[1])

array([ 0,  9, 18,  4])

In [14]:
def getOptionsNext(blueprint, robots_count, materials_count, bpmaxcost):
    #Returns a index of robot to buy or None for not buying

    #Check which robots I can buy with the materials I have
    canIBuy=np.zeros((4),dtype=bool)
    for ibp, bpitem in enumerate(blueprint):
        canIBuy[ibp] = np.all( (materials_count-bpitem)>=0)

    #print(f"canIBuy: {canIBuy}")

    buylist = list( np.nonzero(canIBuy)[0] )
    buylist.append(None)
    #print(f"buylist:{buylist}")

    return buylist

In [24]:
#This is not working well
def getOptionsNext_opt(blueprint, robots_count, materials_count, bpmaxcost):
    #Returns a index of robot to buy or None for not buying

    #Check which robots I can buy with the materials I have
    canIBuy=np.zeros((4),dtype=bool)
    for ibp, bpitem in enumerate(blueprint):
        canIBuy[ibp] = np.all( (materials_count-bpitem)>=0)

        if canIBuy[ibp] and ibp!=0:
            #if materials_count[ibp] >= ( bpmaxcost[ibp] * 2 ):
            #if robots_count[ibp] > bpmaxcost[ibp]+1:
            if robots_count[ibp] >= bpmaxcost[ibp]:
                #No point buying this robot because there are enough robots already to be able to create materials per day for making any other robot
                canIBuy[ibp]=False
        
    #print(f"canIBuy: {canIBuy}")
    
    buylist= [None]
    buylist1 = list( np.nonzero(canIBuy)[0] )
    buylist.extend(buylist1)
    #buylist.append(None)
    #print(f"buylist:{buylist}")

    return buylist


In [16]:
#Global variables
maxgeode_global = 0
already_calculated={}

In [17]:
def maxAtMinute2(blueprint, robots_count, materials_count, minute, maxminutes, bpmaxcost):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    global maxgeode_global
    global already_calculated
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    #Check if there is any chance to get a better result. Number of geode robots and geode materials
    minleft = maxminutes-minute

    #sum(i, from k to k+m = 1/2*(2k+m)(m+1)
    # replace k with robot_count+1, and m with number of minutes
    maxgeodes_possible = int(materials_count[0] +1+ (2*(robots_count[0]+1)+minleft+1)*(minleft+2)/2)

    if maxgeodes_possible<maxgeode_global:
        return materials_count[0] #Get out if it is not possible to do better

    maxgeodes = 0 #default
    
    buylist = getOptionsNext(blueprint, robots_count, materials_count, bpmaxcost)
    #print(f"buylist:{buylist}")
    
    maxgeode0=0

    for buyrobot0 in buylist:
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()
        #print(f"Buying robot {buyrobot0}.")

        if not buyrobot0 is None:
            #Test materials that will be left if we buy the robot
            materials_count1 -= blueprint[buyrobot0]
    
            #print(f"After buying this robot the materials left is {materials_count1}")

        #Update materials based in the number of robots
        materials_count1+= robots_count
        #print(f"Robots collect materials, leading to {materials_count1}")
    
        #Update robot count at end of minute if there was a purchase
        if not buyrobot0 is None:
            robots_count1[buyrobot0]+=1
            #print(f"New robot acquired, robot_count1 is now {robots_count1}")

        minute1 = minute+1
        #Check if reached maximum number of minutes
        if minute1>maxminutes:
            return materials_count1[0]

        #print(f"Entering {minute1} mins...")
        maxgeode0 = maxAtMinute2(blueprint,robots_count1,materials_count1,minute1, maxminutes, bpmaxcost)
        #print(f"{minute} mins, maxgeode0: {maxgeode0}")

        maxgeodes= max(maxgeodes, maxgeode0)

    if maxgeodes>maxgeode_global:
        #print(f"{minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
        
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes

    return maxgeodes

In [18]:
def maxAtMinute2_opt(blueprint, robots_count, materials_count, minute, maxminutes, bpmaxcost):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    global maxgeode_global
    global already_calculated
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    #Check if there is any chance to get a better result. Number of geode robots and geode materials
    minleft = maxminutes-minute

    #sum(i, from k to k+m = 1/2*(2k+m)(m+1)
    # replace k with robot_count+1, and m with number of minutes
    maxgeodes_possible = int(materials_count[0] +1+ (2*(robots_count[0]+1)+minleft+1)*(minleft+2)/2)
    
    if maxgeodes_possible<maxgeode_global:
        return materials_count[0] #Get out if it is not possible to do better

    maxgeodes = 0 #default
    
    buylist = getOptionsNext_opt(blueprint, robots_count, materials_count, bpmaxcost)
    #print(f"buylist:{buylist}")
    
    maxgeode0=0

    for buyrobot0 in buylist:
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()
        #print(f"Buying robot {buyrobot0}.")

        if not buyrobot0 is None:
            #Test materials that will be left if we buy the robot
            materials_count1 -= blueprint[buyrobot0]
    
            #print(f"After buying this robot the materials left is {materials_count1}")

        #Update materials based in the number of robots
        materials_count1+= robots_count
        #print(f"Robots collect materials, leading to {materials_count1}")
    
        #Update robot count at end of minute if there was a purchase
        if not buyrobot0 is None:
            robots_count1[buyrobot0]+=1
            #print(f"New robot acquired, robot_count1 is now {robots_count1}")

        minute1 = minute+1
        #Check if reached maximum number of minutes
        if minute1>maxminutes:
            return materials_count1[0]

        #print(f"Entering {minute1} mins...")
        maxgeode0 = maxAtMinute2_opt(blueprint,robots_count1,materials_count1,minute1, maxminutes, bpmaxcost)
        #print(f"{minute} mins, maxgeode0: {maxgeode0}")

        maxgeodes= max(maxgeodes, maxgeode0)

    if maxgeodes>maxgeode_global:
        #print(f"{minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
        
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes

    return maxgeodes

In [19]:
def maxAtMinute3(blueprint, robots_count, materials_count, minute, maxminutes, bpmaxcost):
    #print(f"** {minute} mins, robots_count: {robots_count}, materials_count:{materials_count}")
    global maxgeode_global
    global already_calculated
    
    #Check if this state has already been calculated
    if (*robots_count, *materials_count, minute) in already_calculated:
        return already_calculated[(*robots_count, *materials_count, minute)]

    #Check if there is any chance to get a better result. Number of geode robots and geode materials
    minleft = maxminutes-minute
    #sum(i, from k to k+m) = 1/2*(2k+m)(m+1)
    # replace k with robot_count+1, and m with number of minutes
    #maxgeodes_possible = materials_count[0] +1+ (2*(robots_count[0]+1)+minleft+1)*(minleft+2)//2
    maxgeodes_possible = materials_count[0] + (2*robots_count[0]+minleft)*(minleft+1)//2
    if maxgeodes_possible<maxgeode_global:
        return materials_count[0] #Get out if it is not possible to do better

    maxgeodes = 0 #default

    # Check if number of robots per material producing for geode is already ok to just create geode robots every minute
    mat_for_geode = blueprint[0]
    if np.all(robots_count>=mat_for_geode) and np.all(materials_count>=mat_for_geode):
        #No need to continue
        #Number of geodes that will be produced will be
        # previous + produced in this minute (ngeoderobots) + (next minute ngeoderobots+1) + ...+ (next minute ngeoderobots+minleft)
        #sum(i, from k to k+m) = 1/2*(2k+m)(m+1)
        #maxgeodes = materials_count[0] + (2*robots_count[0]+minleft)*(minleft+1)//2
        #return maxgeodes
        return maxgeodes_possible
    
    buylist = getOptionsNext_opt(blueprint, robots_count, materials_count, bpmaxcost)
    #print(f"buylist:{buylist}")
    
    maxgeode0=0

    for buyrobot0 in buylist:
        materials_count1 = materials_count.copy() #Hopefully, np array copy properly
        robots_count1 = robots_count.copy()
        #print(f"Buying robot {buyrobot0}.")

        if not buyrobot0 is None:
            #Test materials that will be left if we buy the robot
            materials_count1 -= blueprint[buyrobot0]
    
            #print(f"After buying this robot the materials left is {materials_count1}")

        #Update materials based in the number of robots
        materials_count1+= robots_count
        #print(f"Robots collect materials, leading to {materials_count1}")
    
        #Update robot count at end of minute if there was a purchase
        if not buyrobot0 is None:
            robots_count1[buyrobot0]+=1
            #print(f"New robot acquired, robot_count1 is now {robots_count1}")

        minute1 = minute+1
        #Check if reached maximum number of minutes
        if minute1>maxminutes:
            return materials_count1[0]

        #print(f"Entering {minute1} mins...")
        maxgeode0 = maxAtMinute3(blueprint,robots_count1,materials_count1,minute1, maxminutes, bpmaxcost)
        #print(f"{minute} mins, maxgeode0: {maxgeode0}")

        maxgeodes= max(maxgeodes, maxgeode0)

    if maxgeodes>maxgeode_global:
        #print(f"{minute} min, new geode max: {maxgeodes}")
        maxgeode_global=maxgeodes
        
    already_calculated[(*robots_count, *materials_count, minute)] = maxgeodes

    return maxgeodes

In [20]:
def getMaxGeodesForBlueprint(blueprint, minutes):
    global already_calculated
    global maxgeode_global
    #reset
    maxgeode_global=0
    already_calculated={}

    bpmaxcost = getMaxCost(blueprint)
    #print(f"bpmaxcost:{bpmaxcost}")

    robots_count_init = np.array([0,0,0,1])
    materials_count_init = np.array([0,0,0,0])
    return maxAtMinute2(blueprint, robots_count_init, materials_count_init, 1, minutes, bpmaxcost)

In [21]:
def getMaxGeodesForBlueprint_opt(blueprint, minutes):
    global already_calculated
    global maxgeode_global
    #reset
    maxgeode_global=0
    already_calculated={}

    bpmaxcost = getMaxCost(blueprint)
    #print(f"bpmaxcost:{bpmaxcost}")

    robots_count_init = np.array([0,0,0,1])
    materials_count_init = np.array([0,0,0,0])
    return maxAtMinute2_opt(blueprint, robots_count_init, materials_count_init, 1, minutes, bpmaxcost)

In [22]:
def getMaxGeodesForBlueprint3(blueprint, minutes):
    global already_calculated
    global maxgeode_global
    #reset
    maxgeode_global=0
    already_calculated={}

    bpmaxcost = getMaxCost(blueprint)
    #print(f"bpmaxcost:{bpmaxcost}")

    robots_count_init = np.array([0,0,0,1])
    materials_count_init = np.array([0,0,0,0])
    return maxAtMinute3(blueprint, robots_count_init, materials_count_init, 1, minutes, bpmaxcost)

# Testing

Examples in website

In [ ]:
minutes=24
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 14,  3]),
  np.array([0, 0, 0, 2]),
  np.array([0, 0, 0, 4])]
exp_result = 9
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [25]:
minutes=24
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 14,  3]),
  np.array([0, 0, 0, 2]),
  np.array([0, 0, 0, 4])]
exp_result = 9
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 9 , expected 9


In [ ]:
minutes=24
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([0, 0, 8, 3]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 2])]
exp_result = 12
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [26]:
minutes=24
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([0, 0, 8, 3]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 2])]
exp_result = 12
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 12 , expected 12


Examples from file, already tested at 24 mins

In [ ]:
minutes=24
blueprint = [np.array([0, 9, 0, 4]),
  np.array([ 0,  0, 18,  4]),
  np.array([0, 0, 0, 4]),
  np.array([0, 0, 0, 4])
  ]
exp_result = 0
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [27]:
minutes=24
blueprint = [np.array([0, 9, 0, 4]),
  np.array([ 0,  0, 18,  4]),
  np.array([0, 0, 0, 4]),
  np.array([0, 0, 0, 4])
  ]
exp_result = 0
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 0 , expected 0


In [ ]:
minutes=24
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 10,  4]),
  np.array([0, 0, 0, 4]),
  np.array([0, 0, 0, 4])]
exp_result = 4
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [28]:
minutes=24
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 10,  4]),
  np.array([0, 0, 0, 4]),
  np.array([0, 0, 0, 4])]
exp_result = 4
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 4 , expected 4


In [ ]:
minutes=24
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([ 0,  0, 15,  4]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 4])]
exp_result = 1
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [29]:
minutes=24
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([ 0,  0, 15,  4]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 4])]
exp_result = 1
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 1 , expected 1


Examples from website, with given answers at 32 mins

In [ ]:
minutes=32
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 14,  3]),
  np.array([0, 0, 0, 2]),
  np.array([0, 0, 0, 4])]
exp_result = 56
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [30]:
minutes=32
blueprint = [np.array([0, 7, 0, 2]),
  np.array([ 0,  0, 14,  3]),
  np.array([0, 0, 0, 2]),
  np.array([0, 0, 0, 4])]
exp_result = 56
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

opt3, 56 , expected 56


In [ ]:
minutes=32
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([0, 0, 8, 3]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 2])]
exp_result = 62
print ( "opt,",getMaxGeodesForBlueprint_opt( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

In [ ]:
minutes=32
blueprint = [np.array([ 0, 12,  0,  3]),
  np.array([0, 0, 8, 3]),
  np.array([0, 0, 0, 3]),
  np.array([0, 0, 0, 2])]
exp_result = 62
print ( "opt3,",getMaxGeodesForBlueprint3( blueprint , minutes), f", expected {exp_result}" )
#print ( "non-opt,", getMaxGeodesForBlueprint( blueprint , minutes), f", expected {exp_result}" )

# Calculation

use the non-optimized because is giving better results

In [31]:
values=[]

In [32]:
print(f"Blueprint 1")
bpmax= getMaxGeodesForBlueprint3( blueprints[1] , 32)
print( f"value={bpmax} ")
values.append(bpmax)

Blueprint 1
value=16 


12 is wrong answer, should be 16

In [33]:
print(f"Blueprint 2")
bpmax= getMaxGeodesForBlueprint3( blueprints[2] , 32)
print( f"value={bpmax} ")
values.append(bpmax)

Blueprint 2
value=40 


ok

In [34]:
print(f"Blueprint 3")
bpmax= getMaxGeodesForBlueprint3( blueprints[3] , 32)
print( f"value={bpmax} ")
values.append(bpmax)

Blueprint 3
value=21 


In [35]:
values

[16, 40, 21]

In [36]:
answer = np.prod( np.array(values))
answer

13440

Answer is not 8640