In [35]:
import numpy as np

In [46]:
#filename = "input_test.txt"
filename = "input.txt"

In [47]:
with open(filename, 'r') as f:
    lines = f.read().splitlines()

In [48]:
lines

['.v.v.v>...>vv>v>>>.v>..v>.v.>.>v>.v.v.>>v...>.>....>.>vv>>>.....>>...v.>>v..>..vvv.>v...vv...>..>....>.>.>.>vvv....>..vv>v....>v...>>....v.',
 '>.v>..v.>>vv.>>v...v.>.>..v.>.>.>vvv..>>>.>...>v>.>>v....>>>>...>v.v>.v>....>>>v.>>>....vv.....vvv.v.v..>.>..v>>.>.v>.>v>.vvvv.v..v>>..>>vv',
 '.vv>>...v>..v..v>v.>vvv.v.v>>.....v>>.......>...v>.v>.v.vv.v.>v>v.v......>>......>.v...v........v.v........>.v.vv.>>.v.>>.>.>...v....v>>>..',
 '.>.>v.>vv.v...v.>>v>.>v..vv>..v.v.>...v....>vvvvvv>>>v..vv.v.v>>.>>.>>v>v>>..>.v...v.v.>v..>...v.>.>>.v...v>..v...vv.>v.....vvv.v>.v>..>>v.',
 '..>.....v.>>..>>.v>v.>.>>.>..vv.v>>.>..>.>..v>>...>.>>.vv>>>..>>>>.v.>....>>.>..v>>vv>.>>v>vvvv>vv..v.v.>.v>..v>.vvv>>.v.......>>.>...>>.>.',
 'v...>..>..v>.vv.>>.>...>>....v.......v>...v.vvvvv>..v...>.v.>.>>v>v.>....v>...>...v.>.vv>......vv>.v>vv>>....v>.v>.>..>v.v..>>>.>>>..v..>vv',
 'v>v>.v>..v..v.>..>...>v.>..>.>vvvv...v.v>v....>.>v.vvvv....>...v.v..vvvvvv..v.v..v>v....>v....>v.>>.v>.>v..>...v.vv...>v>>..>.>.....v.

In [49]:
#Get the shape:
shape = (len(lines), len(lines[0]))
shape

(137, 139)

In [50]:
board = np.zeros(shape, dtype=np.uint8)

In [51]:
for iy,l0 in enumerate(lines):
    for ix,c0 in enumerate(l0):
        item = 0
        if c0 =='v' or c0=='V':
            item = 2
        if c0=='>':
            item = 1
        board[iy,ix]=item


In [52]:
board
#1 for east facing
#2 for south facing

array([[0, 2, 0, ..., 0, 2, 0],
       [1, 0, 2, ..., 1, 2, 2],
       [0, 2, 2, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [2, 0, 0, ..., 2, 0, 0],
       [1, 1, 2, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
#Try to move east
#Check spaces available
#Perhaps the best way is to get an array with location of east-facing pieces
#Check available location. shift them left to check overlap
# The (available and piece ) are the ones that will move
# Move the pieces by setting locations marked to available, and set the new locations with the piece

In [14]:
#Shift board array left
board_left = np.zeros_like(board)
board_left[:,:-1] = board[:,1:]
board_left[:,-1] = board[:,0] #last col, circular

In [15]:
board_left

array([[0, 0, 0, 1, 1, 0, 2, 2, 1, 2],
       [2, 2, 1, 1, 0, 2, 2, 0, 0, 0],
       [1, 0, 1, 2, 1, 0, 0, 0, 2, 1],
       [1, 2, 1, 1, 0, 1, 0, 2, 0, 1],
       [1, 2, 0, 2, 2, 0, 2, 0, 0, 2],
       [0, 1, 1, 0, 0, 2, 0, 0, 0, 1],
       [2, 2, 0, 0, 1, 0, 1, 2, 0, 0],
       [0, 2, 0, 0, 1, 1, 2, 0, 2, 2],
       [0, 0, 0, 2, 0, 0, 2, 0, 1, 0]], dtype=uint8)

In [20]:
ef_tomove = np.bitwise_and( board_left==0 , board==1)
ef_tomove

array([[False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False,  True, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True]])

In [25]:
ef_tomove.any()

True

In [21]:
#Shift marked pieces right
pieces_to_move = board*ef_tomove
pieces_to_move_shifted=np.zeros_like(pieces_to_move)
pieces_to_move_shifted[:,1:] = pieces_to_move[:,:-1]
pieces_to_move_shifted[:,0] = pieces_to_move[:,-1]

In [22]:
pieces_to_move_shifted

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [23]:
newboard = np.bitwise_not(ef_tomove) * board + pieces_to_move_shifted

In [24]:
newboard

array([[2, 0, 0, 0, 1, 0, 1, 2, 2, 1],
       [0, 2, 2, 1, 0, 1, 2, 2, 0, 0],
       [1, 0, 1, 1, 2, 0, 1, 0, 0, 2],
       [1, 1, 2, 1, 0, 1, 0, 1, 2, 0],
       [2, 1, 2, 0, 2, 2, 0, 2, 0, 0],
       [0, 1, 1, 0, 1, 0, 2, 0, 0, 0],
       [0, 2, 2, 0, 0, 0, 1, 1, 2, 0],
       [2, 0, 2, 0, 0, 1, 1, 2, 0, 2],
       [1, 0, 0, 0, 2, 0, 0, 2, 0, 0]], dtype=uint8)

In [ ]:
#Move of south facing pieces is similar

In [29]:
board = newboard
board

array([[2, 0, 0, 0, 1, 0, 1, 2, 2, 1],
       [0, 2, 2, 1, 0, 1, 2, 2, 0, 0],
       [1, 0, 1, 1, 2, 0, 1, 0, 0, 2],
       [1, 1, 2, 1, 0, 1, 0, 1, 2, 0],
       [2, 1, 2, 0, 2, 2, 0, 2, 0, 0],
       [0, 1, 1, 0, 1, 0, 2, 0, 0, 0],
       [0, 2, 2, 0, 0, 0, 1, 1, 2, 0],
       [2, 0, 2, 0, 0, 1, 1, 2, 0, 2],
       [1, 0, 0, 0, 2, 0, 0, 2, 0, 0]], dtype=uint8)

In [27]:
#Shift board array up
board_up = np.zeros_like(board)
board_up[:-1,:] = board[1:,:]
board_up[-1,:] = board[0,:] #last row, circular

In [28]:
board_up

array([[0, 2, 2, 1, 0, 1, 2, 2, 0, 0],
       [1, 0, 1, 1, 2, 0, 1, 0, 0, 2],
       [1, 1, 2, 1, 0, 1, 0, 1, 2, 0],
       [2, 1, 2, 0, 2, 2, 0, 2, 0, 0],
       [0, 1, 1, 0, 1, 0, 2, 0, 0, 0],
       [0, 2, 2, 0, 0, 0, 1, 1, 2, 0],
       [2, 0, 2, 0, 0, 1, 1, 2, 0, 2],
       [1, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [2, 0, 0, 0, 1, 0, 1, 2, 2, 1]], dtype=uint8)

In [30]:
sf_tomove = np.bitwise_and( board_up==0 , board==2)
sf_tomove

array([[ True, False, False, False, False, False, False, False,  True,
        False],
       [False,  True, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False,  True,
        False],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [31]:
#Shift marked pieces south
pieces_to_move = board*sf_tomove
pieces_to_move_shifted=np.zeros_like(pieces_to_move)
pieces_to_move_shifted[1:,:] = pieces_to_move[:-1,:]
pieces_to_move_shifted[0,:] = pieces_to_move[-1,:]

In [32]:
pieces_to_move_shifted

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [2, 0, 0, 0, 0, 2, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 2]], dtype=uint8)

In [33]:
newboard = np.bitwise_not(sf_tomove) * board + pieces_to_move_shifted

In [34]:
newboard

array([[0, 0, 0, 0, 1, 0, 1, 2, 0, 1],
       [2, 0, 2, 1, 0, 1, 2, 0, 2, 0],
       [1, 2, 1, 1, 0, 0, 1, 2, 0, 0],
       [1, 1, 2, 1, 2, 1, 0, 1, 0, 2],
       [0, 1, 2, 0, 2, 0, 0, 0, 2, 0],
       [2, 1, 1, 0, 1, 2, 2, 2, 0, 0],
       [0, 0, 2, 0, 0, 0, 1, 1, 0, 0],
       [2, 2, 0, 0, 0, 1, 1, 2, 2, 0],
       [1, 0, 2, 0, 2, 0, 0, 2, 0, 2]], dtype=uint8)

In [53]:
# Loop east - south moves iteratively

board0=np.copy(board)
step = 0
while True:

    # *** East facing ***
    #Shift board array left
    board_left = np.zeros_like(board0)
    board_left[:,:-1] = board0[:,1:]
    board_left[:,-1] = board0[:,0] #last col, circular

    ef_tomove = np.bitwise_and( board_left==0 , board0==1)

    #Shift marked pieces right
    pieces_to_move = board0*ef_tomove
    pieces_to_move_shifted=np.zeros_like(pieces_to_move)
    pieces_to_move_shifted[:,1:] = pieces_to_move[:,:-1]
    pieces_to_move_shifted[:,0] = pieces_to_move[:,-1]

    newboard = np.bitwise_not(ef_tomove) * board0 + pieces_to_move_shifted

    # *** South facing ***
    board0=newboard

    #Shift board array up
    board_up = np.zeros_like(board0)
    board_up[:-1,:] = board0[1:,:]
    board_up[-1,:] = board0[0,:] #last row, circular

    sf_tomove = np.bitwise_and( board_up==0 , board0==2)

    pieces_to_move = board0*sf_tomove
    pieces_to_move_shifted=np.zeros_like(pieces_to_move)
    pieces_to_move_shifted[1:,:] = pieces_to_move[:-1,:]
    pieces_to_move_shifted[0,:] = pieces_to_move[-1,:]

    newboard = np.bitwise_not(sf_tomove) * board0 + pieces_to_move_shifted

    step+=1

    print(f"step {step}")
    #print(newboard)

    board0=newboard

    #Check if any movement has occured
    hasMovementOccurred = ef_tomove.any() or sf_tomove.any()
    if not hasMovementOccurred:
        break

print(f"number of steps until stop = {step}")

step 1
step 2
step 3
step 4
step 5
step 6
step 7
step 8
step 9
step 10
step 11
step 12
step 13
step 14
step 15
step 16
step 17
step 18
step 19
step 20
step 21
step 22
step 23
step 24
step 25
step 26
step 27
step 28
step 29
step 30
step 31
step 32
step 33
step 34
step 35
step 36
step 37
step 38
step 39
step 40
step 41
step 42
step 43
step 44
step 45
step 46
step 47
step 48
step 49
step 50
step 51
step 52
step 53
step 54
step 55
step 56
step 57
step 58
step 59
step 60
step 61
step 62
step 63
step 64
step 65
step 66
step 67
step 68
step 69
step 70
step 71
step 72
step 73
step 74
step 75
step 76
step 77
step 78
step 79
step 80
step 81
step 82
step 83
step 84
step 85
step 86
step 87
step 88
step 89
step 90
step 91
step 92
step 93
step 94
step 95
step 96
step 97
step 98
step 99
step 100
step 101
step 102
step 103
step 104
step 105
step 106
step 107
step 108
step 109
step 110
step 111
step 112
step 113
step 114
step 115
step 116
step 117
step 118
step 119
step 120
step 121
step 122
step 123
s