In [1]:
import numpy as np

In [2]:
#Read data
#filename = "data_test.txt"
filename = "data.txt"
with open(filename,"r") as f:
    text_lines = f.readlines()

In [3]:
text_lines

['692,826 -> 692,915\n',
 '914,338 -> 524,728\n',
 '77,505 -> 77,912\n',
 '31,484 -> 250,703\n',
 '29,241 -> 313,241\n',
 '381,70 -> 381,121\n',
 '699,595 -> 641,595\n',
 '69,989 -> 517,989\n',
 '99,755 -> 99,687\n',
 '205,77 -> 844,77\n',
 '754,705 -> 754,720\n',
 '739,884 -> 739,737\n',
 '504,463 -> 854,113\n',
 '85,386 -> 416,717\n',
 '39,456 -> 449,46\n',
 '900,469 -> 900,462\n',
 '137,680 -> 137,713\n',
 '797,792 -> 264,792\n',
 '814,750 -> 86,22\n',
 '252,644 -> 491,644\n',
 '932,162 -> 932,615\n',
 '42,71 -> 464,71\n',
 '924,685 -> 755,685\n',
 '729,610 -> 729,391\n',
 '921,369 -> 921,649\n',
 '833,241 -> 101,241\n',
 '822,459 -> 507,459\n',
 '739,74 -> 807,142\n',
 '573,850 -> 573,619\n',
 '888,60 -> 888,592\n',
 '133,272 -> 339,66\n',
 '882,662 -> 665,662\n',
 '572,499 -> 959,112\n',
 '631,173 -> 404,173\n',
 '886,730 -> 470,730\n',
 '116,435 -> 980,435\n',
 '795,299 -> 886,390\n',
 '321,464 -> 321,785\n',
 '210,477 -> 210,880\n',
 '215,191 -> 59,347\n',
 '921,749 -> 363,191\n

In [4]:
def get_movement(s):
    s = s.strip()
    orig_dest_s =  s.split('->')
    x0,y0 = orig_dest_s[0].split(',')
    x0 = int(x0)
    y0 = int(y0)

    x1,y1 = orig_dest_s[1].split(',')
    x1 = int(x1)
    y1 = int(y1)

    return x0, y0 , x1, y1

In [5]:
movements = list(map(get_movement,text_lines))

In [6]:
movements

[(692, 826, 692, 915),
 (914, 338, 524, 728),
 (77, 505, 77, 912),
 (31, 484, 250, 703),
 (29, 241, 313, 241),
 (381, 70, 381, 121),
 (699, 595, 641, 595),
 (69, 989, 517, 989),
 (99, 755, 99, 687),
 (205, 77, 844, 77),
 (754, 705, 754, 720),
 (739, 884, 739, 737),
 (504, 463, 854, 113),
 (85, 386, 416, 717),
 (39, 456, 449, 46),
 (900, 469, 900, 462),
 (137, 680, 137, 713),
 (797, 792, 264, 792),
 (814, 750, 86, 22),
 (252, 644, 491, 644),
 (932, 162, 932, 615),
 (42, 71, 464, 71),
 (924, 685, 755, 685),
 (729, 610, 729, 391),
 (921, 369, 921, 649),
 (833, 241, 101, 241),
 (822, 459, 507, 459),
 (739, 74, 807, 142),
 (573, 850, 573, 619),
 (888, 60, 888, 592),
 (133, 272, 339, 66),
 (882, 662, 665, 662),
 (572, 499, 959, 112),
 (631, 173, 404, 173),
 (886, 730, 470, 730),
 (116, 435, 980, 435),
 (795, 299, 886, 390),
 (321, 464, 321, 785),
 (210, 477, 210, 880),
 (215, 191, 59, 347),
 (921, 749, 363, 191),
 (598, 962, 924, 636),
 (105, 70, 105, 411),
 (617, 221, 617, 958),
 (383, 403,

In [7]:
movements_np = np.array(movements)

In [8]:
movements_np

array([[692, 826, 692, 915],
       [914, 338, 524, 728],
       [ 77, 505,  77, 912],
       ...,
       [ 90, 128,  90, 648],
       [ 69, 442,  69, 675],
       [872, 108,  18, 962]])

In [9]:
max_coord = np.max(movements_np) +1
max_coord

990

In [10]:
def sortasc(x0,x1):
    if x0>x1:
        x2 = x0
        x0 = x1
        x1 = x2
    return x0,x1

In [11]:
world = np.zeros((max_coord, max_coord), dtype=np.int32)
for i in range(movements_np.shape[0]):
    #Get origin and end
    movement = movements_np[i]
    print(f"movement = {movement}")
    x0, y0, x1, y1  = movement

    #Horizontal or vertical
    if x0 == x1 or y0==y1:
        isHoriz = True #default
        if x0==x1:
            isHoriz = False
        
        if isHoriz:
            print("Horizontal")
            #add ones to the area
            x0,x1 = sortasc(x0,x1)
            world[y0, x0:x1+1] += np.ones((x1-x0+1), dtype=np.int32)
        else: #vertical
            print("Vertical")
            y0,y1 = sortasc(y0,y1)
            world[y0:y1+1, x0] += np.ones((y1-y0+1), dtype=np.int32)
    else:
        print("Ignore movement as it is diagonal")
    print(world)


movement = [692 826 692 915]
Vertical
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
movement = [914 338 524 728]
Ignore movement as it is diagonal
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
movement = [ 77 505  77 912]
Vertical
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
movement = [ 31 484 250 703]
Ignore movement as it is diagonal
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
movement = [ 29 241 313 241]
Horizontal
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
movement = [381  70 381 121]
Vertical
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
world

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
overlap = np.where(world >=2 ,1,0)

In [14]:
overlap

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
overlap_sum = np.sum(overlap)
overlap_sum #ok

5698