In [25]:
TEST = False

INPUT_FN = "input_test.txt"
TEST_SOLUTION = 13
TEST_SOLUTION2 = 43

if not TEST:
    INPUT_FN = "input.txt"

def printd(s):
    if TEST:
        print (s)

In [26]:
# with open(INPUT_FN) as f:
#     s = f.read()

# patterns_block, designs_block = s.split('\n\n')

# Read and split lines
with open(INPUT_FN) as f:
    lines = [l.rstrip() for l in f]

if lines[-1]=='':
    lines=lines[:,-1]

In [27]:
lines

['....@.@..@@@@.@.@@@@@@@@@@..@@@.@@@@@.@....@.@@@.@@.@@..@@@.@.@@@@@.@.@@@@@.@@@@@@.@@@@@@@.@@@..@.@...@@@..@.@@@@@@.@..@@@@@.@@@.@@.@@@@@.@',
 '@@..@@.@@@@.@@...@...@@.@@.....@@..@@@@....@@.@.@@@@@...@@@@.@.@@@.@@@@..@.@@@@@@.@@..@@.@@.@@@@@...@@.@@@.@@@.@@@.@..@.@.@@@@@@.@@.@@.@@.@',
 '@@@.@.@@@.@@@...@@@@@.@@@@@@..@@@@@@@@.@@.@@@.@.@.@.@@@@@@.@.@.@.@.@@@@@@@@@@@@@@@.@..@@@@.@@.@...@@.@..@.@@@@...@@@@@@@@@.@@@@.@@@@@@....@',
 '@...@.@@@..@@@@@.@@.@@..@@.@@@.@@.@..@@.@.@@.@.@@@..@.@@..@.@@@.@..@@@.@.@@@@@.@@@@@@@@@.@.@.@..@@.@@@.@@..@...@@.@@.@.@.@@@.@@.@@.@@@@.@@@',
 '@@@@..@@@@@@@@@@@@@.@@@@@@...@@.@@@@@@.@@@....@@.@@@@@.@@..@@..@@..@@.@...@@..@@@@@.@@@@@@@@@.....@@.@@.@.@@@.@..@@.@@..@..@.@@.@@@@..@..@@',
 '@@.@@@@@..@@.@@@@@..@@@.@@.@..@@@......@@.@@@@.@@@@@@.@@..@@@@@@@...@@@..@@@@@.@@.@..@@@@@.@@.@@.@.@..@.@@.@@..@.@@@.@@@...@@..@..@@@@@@@@@',
 '@.@@@@..@.@@@@@@@@@@@@@@@@.@@@@@@@@.@.@....@.@..@..@..@@@@.@@@@@@@@.@@@@.@@@.@.@@@@.@@@..@@@@.@@.@@.@@@@.@..@..@@@@@@...@.@....@@@.@@.

# Algorithm

Just count the rolls with counts. Iterate through all the rolls

In [28]:
nrows = len(lines)
ncols = len(lines[0])

In [29]:
import numpy as np
counter = np.zeros( (nrows,ncols), dtype=np.uint32 )
mask = np.zeros_like(counter, dtype=bool)

In [30]:
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(139, 139))

In [31]:
roll_neighbours_count = np.ma.array( counter, mask=mask)

In [32]:
roll_neighbours_count.mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(139, 139))

In [33]:
for irow,line in enumerate(lines):
    for icol,c in enumerate(line):
        if c == '@':
            #check neighbours
            dirs = []
            if irow>0:
                dirs.append((-1,0))
                if icol>0:
                    dirs.append((-1,-1))
                if icol<ncols-1:
                    dirs.append((-1,1))
            if irow<nrows-1:
                dirs.append((1,0))
                if icol>0:
                    dirs.append((1,-1))
                if icol<ncols-1:
                    dirs.append((1,1))
            if icol>0:
                dirs.append((0,-1))
            if icol<ncols-1:
                dirs.append((0,1))

            for dir in dirs:
                irow1, icol1 = ( irow+dir[0], icol+dir[1] )

                c1 = lines[irow1][icol1]
                if c1 == '@':
                    roll_neighbours_count[irow,icol]+=1
        else:
            roll_neighbours_count.mask[irow,icol]=True

In [34]:
roll_neighbours_count

masked_array(
  data=[[--, --, --, ..., 3, --, 1],
        [3, 4, --, ..., 3, --, 2],
        [4, 5, 2, ..., --, --, 3],
        ...,
        [--, --, 4, ..., 6, 6, --],
        [--, --, 5, ..., 4, 5, 3],
        [1, 2, --, ..., --, --, 2]],
  mask=[[ True,  True,  True, ..., False,  True, False],
        [False, False,  True, ..., False,  True, False],
        [False, False, False, ...,  True,  True, False],
        ...,
        [ True,  True, False, ..., False, False,  True],
        [ True,  True, False, ..., False, False, False],
        [False, False,  True, ...,  True,  True, False]],
  fill_value=np.uint64(999999),
  dtype=uint32)

In [35]:
access_rolls = roll_neighbours_count<4
access_rolls

masked_array(
  data=[[--, --, --, ..., True, --, True],
        [True, False, --, ..., True, --, True],
        [False, False, True, ..., --, --, True],
        ...,
        [--, --, False, ..., False, False, --],
        [--, --, False, ..., False, False, True],
        [True, True, --, ..., --, --, True]],
  mask=[[ True,  True,  True, ..., False,  True, False],
        [False, False,  True, ..., False,  True, False],
        [False, False, False, ...,  True,  True, False],
        ...,
        [ True,  True, False, ..., False, False,  True],
        [ True,  True, False, ..., False, False, False],
        [False, False,  True, ...,  True,  True, False]],
  fill_value=True)

In [36]:
result = np.sum(access_rolls)

In [37]:
if TEST:
    assert result== TEST_SOLUTION

print(int(result))


1486


# Part2

Remove, remove, until stop

Convert map to boolean grid

Mark to be removed

Remove at next iteration

In [38]:
rolls_map = np.zeros_like(counter, dtype=bool)

for irow,line in enumerate(lines):
    for icol,c in enumerate(line):
        if c=='@':
            rolls_map[irow,icol] = True
        else:
            rolls_map[irow,icol]=False

In [39]:
rolls_map

array([[False, False, False, ...,  True, False,  True],
       [ True,  True, False, ...,  True, False,  True],
       [ True,  True,  True, ..., False, False,  True],
       ...,
       [False, False,  True, ...,  True,  True, False],
       [False, False,  True, ...,  True,  True,  True],
       [ True,  True, False, ..., False, False,  True]], shape=(139, 139))

Rewrite the algorithm to pick rolls to remove and then remove iteratively

In [40]:
rolls_map0 = rolls_map.copy()
count0 = np.sum(rolls_map0)
print(f"{count0}")

while True:
    counter = np.zeros_like( rolls_map0 , dtype=np.uint32 )
    mask = np.zeros_like(rolls_map0, dtype=bool)

    roll_neighbours_count = np.ma.array( counter, mask=mask)

    roll_neighbours_count
    for irow in range(nrows):
        for icol in range(ncols):
            if rolls_map0[irow,icol]:
                #check neighbours
                dirs = []
                if irow>0:
                    dirs.append((-1,0))
                    if icol>0:
                        dirs.append((-1,-1))
                    if icol<ncols-1:
                        dirs.append((-1,1))
                if irow<nrows-1:
                    dirs.append((1,0))
                    if icol>0:
                        dirs.append((1,-1))
                    if icol<ncols-1:
                        dirs.append((1,1))
                if icol>0:
                    dirs.append((0,-1))
                if icol<ncols-1:
                    dirs.append((0,1))

                for dir in dirs:
                    irow1, icol1 = ( irow+dir[0], icol+dir[1] )

                    if rolls_map0[irow1,icol1]:
                        roll_neighbours_count[irow,icol]+=1
            else:
                roll_neighbours_count.mask[irow,icol]=True
    
    access_rolls = roll_neighbours_count<4
    # here the rolls to be removed will be marked
    sum_access_rolls  = np.sum(access_rolls)
    print(f"{sum_access_rolls=}")
    if sum_access_rolls==0:
        print("No more rolls to remove. Exiting")
        break

    # remove them

    rolls_map1 = np.logical_not( np.logical_and(rolls_map0, access_rolls))

    rolls_map0 = rolls_map1 #next iteration

count1= np.sum(rolls_map1)

12563
sum_access_rolls=np.int64(1486)
sum_access_rolls=np.int64(1128)
sum_access_rolls=np.int64(882)
sum_access_rolls=np.int64(690)
sum_access_rolls=np.int64(589)
sum_access_rolls=np.int64(472)
sum_access_rolls=np.int64(405)
sum_access_rolls=np.int64(362)
sum_access_rolls=np.int64(304)
sum_access_rolls=np.int64(266)
sum_access_rolls=np.int64(239)
sum_access_rolls=np.int64(208)
sum_access_rolls=np.int64(197)
sum_access_rolls=np.int64(180)
sum_access_rolls=np.int64(158)
sum_access_rolls=np.int64(135)
sum_access_rolls=np.int64(129)
sum_access_rolls=np.int64(107)
sum_access_rolls=np.int64(95)
sum_access_rolls=np.int64(96)
sum_access_rolls=np.int64(83)
sum_access_rolls=np.int64(84)
sum_access_rolls=np.int64(71)
sum_access_rolls=np.int64(59)
sum_access_rolls=np.int64(61)
sum_access_rolls=np.int64(55)
sum_access_rolls=np.int64(46)
sum_access_rolls=np.int64(44)
sum_access_rolls=np.int64(46)
sum_access_rolls=np.int64(42)
sum_access_rolls=np.int64(33)
sum_access_rolls=np.int64(31)
sum_access_rol

In [41]:
rolls_removed = count0-count1

In [42]:
if TEST:
    assert rolls_removed== TEST_SOLUTION2

print(rolls_removed)

9024
