In [1]:
import numpy as np

In [2]:
#filename ="data_test.txt"
filename="input.txt"

In [3]:
#Work out a way to read input data
with open(filename,"r") as f:
    lines = f.read().splitlines()

In [4]:
scanners = {}

currentscanner = None
beacons_coords = []
for l0 in lines:
    if l0.find("scanner")>=0:
        #next lines are scanner data
        svalue = int(l0.strip("-").strip( ).strip("scanner"))
        currentscanner = svalue
        print(f"New scanner {currentscanner} data")
        scanners[currentscanner]={} #Set new dict value
        beacons_coords=[]
    else:
        if l0=="":
            #End of scanner data
            scanners[currentscanner] =  np.array(beacons_coords)
        else:
            beacons_coords.append( list(map(int,l0.split(","))))

#Store last scanner data
if len(beacons_coords):
     scanners[currentscanner] = np.array(beacons_coords)


New scanner 0 data
New scanner 1 data
New scanner 2 data
New scanner 3 data
New scanner 4 data
New scanner 5 data
New scanner 6 data
New scanner 7 data
New scanner 8 data
New scanner 9 data
New scanner 10 data
New scanner 11 data
New scanner 12 data
New scanner 13 data
New scanner 14 data
New scanner 15 data
New scanner 16 data
New scanner 17 data
New scanner 18 data
New scanner 19 data
New scanner 20 data
New scanner 21 data
New scanner 22 data
New scanner 23 data
New scanner 24 data
New scanner 25 data
New scanner 26 data
New scanner 27 data
New scanner 28 data
New scanner 29 data
New scanner 30 data
New scanner 31 data
New scanner 32 data
New scanner 33 data
New scanner 34 data
New scanner 35 data


In [5]:
scanners[0]

array([[ 417,  597, -659],
       [-781, -790, -526],
       [   1, -140,   -9],
       [ 311,  816,  519],
       [ 274,  815,  564],
       [ -89,   11, -167],
       [-842, -411,  466],
       [-760,  591, -661],
       [-831, -483,  469],
       [-831, -515,  455],
       [-826,  643, -605],
       [-794, -873, -582],
       [ 378, -780, -402],
       [-864,  635, -645],
       [ 369, -725, -496],
       [ 587, -558,  577],
       [-973,  480,  540],
       [-723, -955, -453],
       [ 406, -622, -430],
       [ 510,  768, -630],
       [-845,  401,  529],
       [ 492,  744, -683],
       [ 618, -598,  694],
       [-898,  460,  422],
       [ 630, -610,  724],
       [ 313,  739,  706]])

In [6]:
#How it lookes when trying to loccate a single element in this way
scanners[0] == [ 455,  729,  728]
#A vector that is found will show as [True, True, True]

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [7]:
(scanners[0] == [ 455,  729,  728]).all(axis=1) #Logical AND across the vector

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [8]:
np.where( (scanners[0] == [ 455,  729,  728]).all(axis=1) ) #Get the index where the vector was found

(array([], dtype=int64),)

In [9]:
np.sum((scanners[0] == [ 455,  729,  728]).all(axis=1))  # Number of matches

0

In [10]:
scan_temp = np.copy(scanners[0])

In [11]:
#np.delete, remove elements at the indices given in the second parameter
# If second parameter are numbers, removes the indices given
# If it is a boolean array, removes the elements indicated with true

#OK, it works
np.delete(scan_temp, (scan_temp == [ 404, -588, -901]).all(axis=1) , axis=0)

array([[ 417,  597, -659],
       [-781, -790, -526],
       [   1, -140,   -9],
       [ 311,  816,  519],
       [ 274,  815,  564],
       [ -89,   11, -167],
       [-842, -411,  466],
       [-760,  591, -661],
       [-831, -483,  469],
       [-831, -515,  455],
       [-826,  643, -605],
       [-794, -873, -582],
       [ 378, -780, -402],
       [-864,  635, -645],
       [ 369, -725, -496],
       [ 587, -558,  577],
       [-973,  480,  540],
       [-723, -955, -453],
       [ 406, -622, -430],
       [ 510,  768, -630],
       [-845,  401,  529],
       [ 492,  744, -683],
       [ 618, -598,  694],
       [-898,  460,  422],
       [ 630, -610,  724],
       [ 313,  739,  706]])

In [12]:
def countOverlapAndAppendWithNoDuplicates(scandata0, scandata1):

    allb1_in_sd0 = None
    for b1 in scandata1:
        b1_in_sd0 = (scandata0 == b1).all(axis=1) #boolean matrix where element was found
        if allb1_in_sd0 is None:
            allb1_in_sd0 = b1_in_sd0 #First element initialises
        else:
            #Accumulate
            allb1_in_sd0 = np.logical_or(allb1_in_sd0, b1_in_sd0)
    
    noverlaps = np.sum(allb1_in_sd0)

    newscan=None

    if noverlaps>=12:
        print(f"{noverlaps} >=12 overlaps . Appending and removing duplicates")
        #Remove duplicates
        #addedscan = np.copy(scandata1)
        addedscan = np.delete ( scandata0 , allb1_in_sd0, axis=0)

        #Appends
        newscan = np.append(addedscan, scandata1, axis=0)
    
    return newscan, noverlaps

In [13]:
#Test
countOverlapAndAppendWithNoDuplicates(scanners[0], scanners[4])

(None, 0)

In [14]:
rotateZBy90Matrix = [   [  0 , -1 ,  0 ] ,
                        [  1 ,  0 ,  0 ] ,
                        [  0 ,  0 ,  1 ]
                    ]

rotateYBy90Matrix = [   [  0 ,  0 ,  1 ] ,
                        [  0 ,  1 ,  0 ] ,
                        [ -1 ,  0 ,  0 ]
                    ]

rotateXByMinus90Matrix = [  [  1 ,  0 ,  0 ] ,
                            [  0 ,  0 ,  1 ] ,
                            [  0 , -1 ,  0 ]
                        ]


In [15]:
#Maybe too slow
def applyTransformToScannerData(scannerdata, transfmatrix):
    scannerdata_rot = np.copy(scannerdata)

    for i in range(len(scannerdata)):
        scannerdata_rot[i] = np.matmul(transfmatrix, scannerdata[i])

    return scannerdata_rot

In [16]:
#Test
applyTransformToScannerData(scanners[0] , rotateXByMinus90Matrix)

array([[ 417, -659, -597],
       [-781, -526,  790],
       [   1,   -9,  140],
       [ 311,  519, -816],
       [ 274,  564, -815],
       [ -89, -167,  -11],
       [-842,  466,  411],
       [-760, -661, -591],
       [-831,  469,  483],
       [-831,  455,  515],
       [-826, -605, -643],
       [-794, -582,  873],
       [ 378, -402,  780],
       [-864, -645, -635],
       [ 369, -496,  725],
       [ 587,  577,  558],
       [-973,  540, -480],
       [-723, -453,  955],
       [ 406, -430,  622],
       [ 510, -630, -768],
       [-845,  529, -401],
       [ 492, -683, -744],
       [ 618,  694,  598],
       [-898,  422, -460],
       [ 630,  724,  610],
       [ 313,  706, -739]])

In [17]:
def applyTransformToScannerData2(scannerdata, transfmatrix):
    scannerdata_rot = np.transpose ( np.matmul( transfmatrix , np.transpose(scannerdata)))

    return scannerdata_rot

In [18]:
#Test
applyTransformToScannerData2(scanners[0] , rotateXByMinus90Matrix)

array([[ 417, -659, -597],
       [-781, -526,  790],
       [   1,   -9,  140],
       [ 311,  519, -816],
       [ 274,  564, -815],
       [ -89, -167,  -11],
       [-842,  466,  411],
       [-760, -661, -591],
       [-831,  469,  483],
       [-831,  455,  515],
       [-826, -605, -643],
       [-794, -582,  873],
       [ 378, -402,  780],
       [-864, -645, -635],
       [ 369, -496,  725],
       [ 587,  577,  558],
       [-973,  540, -480],
       [-723, -453,  955],
       [ 406, -430,  622],
       [ 510, -630, -768],
       [-845,  529, -401],
       [ 492, -683, -744],
       [ 618,  694,  598],
       [-898,  422, -460],
       [ 630,  724,  610],
       [ 313,  706, -739]])

In [19]:
#Another faster method
#create all rotation matrices
all24RotationTransforms = []

#Invert or not invert up direction
for invz in [1,-1]:
    invertmatrix = np.eye(3,3)
    #print(f"invz = {invz}")
    if invz==-1:
        #Turn it around by  rotating 180 around yy
        invertmatrix=np.matmul(rotateYBy90Matrix, rotateYBy90Matrix)

    #Rotation around z
    rotZMatrix = np.eye(3,3)
    for izrot in range(4):
        #print(f"izrot = {izrot}")
        if izrot >=1:
            rotZMatrix = np.matmul( rotateZBy90Matrix, rotZMatrix)

        #Rotation to face the different axis
        rotFaceDiffAxis = None
        for facerot in ('none', 'ztox', 'ztoy'):
            #print(f"facerot = {facerot}")
            scandata1_3 = None
            if facerot=='none':
                rotFaceDiffAxis = np.eye(3,3)
            elif facerot=='ztox':
                rotFaceDiffAxis = rotateYBy90Matrix
            elif facerot == 'ztoy':
                rotFaceDiffAxis = rotateXByMinus90Matrix
            
            #transformatrix = np.matmul( rotZMatrix , np.matmul(rotFaceDiffAxis ,invertmatrix) )
            transformatrix = np.matmul( rotFaceDiffAxis , np.matmul(rotZMatrix ,invertmatrix) )

            info = f"invz={invz} ; izrot={izrot} ; facerot={facerot}"

            all24RotationTransforms.append([transformatrix,info])

In [20]:
len(all24RotationTransforms) #size OK

24

In [21]:
def checkFor12Overlaps(scandata0, scandata1):
    #Parameters scandata0 and scandata1 are the scandata from each, as a numpy array
    #Returns the new scan data with appended and duplicates removed
    # and the 3D translation that the 2nd volume needs in order to get 12 beacons to match

    #overlap_scan_data = None

    for beacon0 in scandata0:
        for beacon1 in scandata1:
            #Translate scandata in second volume by vector
            translvector = beacon1-beacon0

            scandata1_transl = scandata1 - translvector #TODO: Check it adds to every row
            
            newscan , noverlaps = countOverlapAndAppendWithNoDuplicates(scandata0, scandata1_transl)

            #print(f"noverlaps = {noverlaps}")

            #print(f"b0:{beacon0} , b1:{beacon1} ; Translate beacon1 by : {translvector}")
            if noverlaps>=12:
                print ("Found >12 overlaps, returning the matched scan data")
                return newscan, translvector
            else:
                #print("No >12 overlap found")
                pass
    
    return None, None


In [22]:
def checkFor12OverlapsInAllOrientations3(scandata0,scandata1):
    for transform , info in all24RotationTransforms:
        #scandata1_trans = applyTransformToScannerData(scandata1, transform)
        scandata1_trans = applyTransformToScannerData2(scandata1, transform)

        #Now we can check for overlaps
        newscan, translvector = checkFor12Overlaps(scandata0, scandata1_trans)
        if not newscan is None:
            print(f"Overlap found with {info} , translate: {translvector}")
            return newscan
    return None

In [23]:
#Test
checkFor12OverlapsInAllOrientations3(scanners[0],scanners[1]) #There should be overlap

In [24]:
#Test
checkFor12OverlapsInAllOrientations3(scanners[1],scanners[4]) #There should be overlap

## Run the whole scanner data

In [25]:
iscannersleft = list(np.arange(1,len(scanners)))

wholescan = np.copy(scanners[0]) # initialises

hasfoundmatch=True
while len(iscannersleft)>0 and hasfoundmatch:
    iscannersleft0 = iscannersleft.copy()
    hasfoundmatch=False
    for scannumb in iscannersleft0:
        print(f"scanner_numb = {scannumb}")
        #res = checkFor12OverlapsInAllOrientations2(wholescan, scanners0[scannumb])
        newscan = checkFor12OverlapsInAllOrientations3(wholescan, scanners[scannumb])

        if not newscan is None:
            wholescan = newscan
            iscannersleft.remove(scannumb)
            hasfoundmatch=True
    if not hasfoundmatch:
        print(f"No more matchings found, but with scanners {iscannersleft} to be matched. Exiting.")


scanner_numb = 1
scanner_numb = 2
scanner_numb = 3
scanner_numb = 4
scanner_numb = 5
12 >=12 overlaps . Appending and removing duplicates
Found >12 overlaps, returning the matched scan data
Overlap found with invz=1 ; izrot=1 ; facerot=none , translate: [  108. -1136.    57.]
scanner_numb = 6
scanner_numb = 7
scanner_numb = 8
scanner_numb = 9
scanner_numb = 10
scanner_numb = 11
12 >=12 overlaps . Appending and removing duplicates
Found >12 overlaps, returning the matched scan data
Overlap found with invz=1 ; izrot=3 ; facerot=ztox , translate: [ 104.   60. 1191.]
scanner_numb = 12
scanner_numb = 13
scanner_numb = 14
scanner_numb = 15
scanner_numb = 16
scanner_numb = 17
scanner_numb = 18
scanner_numb = 19
scanner_numb = 20
12 >=12 overlaps . Appending and removing duplicates
Found >12 overlaps, returning the matched scan data
Overlap found with invz=1 ; izrot=1 ; facerot=ztoy , translate: [  28.   99. 2459.]
scanner_numb = 21
scanner_numb = 22
scanner_numb = 23
scanner_numb = 24
scanner

In [26]:
wholescan

array([[ 1.000e+00, -1.400e+02, -9.000e+00],
       [-8.900e+01,  1.100e+01, -1.670e+02],
       [-8.420e+02, -4.110e+02,  4.660e+02],
       ...,
       [-2.917e+03,  6.701e+03, -2.808e+03],
       [-4.511e+03,  6.659e+03, -4.491e+03],
       [-4.584e+03,  6.575e+03, -2.976e+03]])

In [27]:
len(wholescan)

447

In [28]:
np.save("wholescan.txt",wholescan)