In [1]:
import numpy as np

In [2]:
def getManhatanDistance(vector0, vector1):
    deltavector = np.abs(vector1-vector0)
    return np.sum(deltavector)

In [4]:
#Test
vector0 = np.array( [1105 , -1205 , 1229] )
vector1 = np.array( [ -92, -2380, -20 ] )
getManhatanDistance(vector0, vector1)

3621

## Using wholescan calculation output

In [8]:
with open("calc_beacon_output.txt","r") as f:
    lines = f.read().splitlines()

In [25]:
a = str(np.array([10,2,3]))
print(a)
a1 = a.strip('[]')
print(a1)
b= np.fromstring(a1, sep=" ")
print(b)

[10  2  3]
10  2  3
[10.  2.  3.]


In [47]:
beacon_poss = np.array([[0,0,0]])
iscanner=1

for l0 in lines:

    translpos = l0.find("translate:")
    #print(f"translpos={translpos}")

    if translpos>=0:
        #Get the value
        s = l0[ translpos+10:]
        print(f"string : {s}")
        s0 = s.strip('[ ]')
        print(f"s0={s0}")
        scanpos = np.fromstring( s0 , sep=" ")
        print(f"scanner {iscanner} at position {scanpos}")
        beacon_poss = np.append(beacon_poss,[scanpos] , axis=0)
        iscanner+=1

string :  [  108. -1136.    57.]
s0=108. -1136.    57.
scanner 1 at position [  108. -1136.    57.]
string :  [ 104.   60. 1191.]
s0=104.   60. 1191.
scanner 2 at position [ 104.   60. 1191.]
string :  [  28.   99. 2459.]
s0=28.   99. 2459.
scanner 3 at position [  28.   99. 2459.]
string :  [   55. -1183.  2527.]
s0=55. -1183.  2527.
scanner 4 at position [   55. -1183.  2527.]
string :  [  101. -2413.   146.]
s0=101. -2413.   146.
scanner 5 at position [  101. -2413.   146.]
string :  [1219.   79. 2541.]
s0=1219.   79. 2541.
scanner 6 at position [1219.   79. 2541.]
string :  [ 158. 1274. 2455.]
s0=158. 1274. 2455.
scanner 7 at position [ 158. 1274. 2455.]
string :  [ 186. 2456. 2380.]
s0=186. 2456. 2380.
scanner 8 at position [ 186. 2456. 2380.]
string :  [ 139. 3642. 2490.]
s0=139. 3642. 2490.
scanner 9 at position [ 139. 3642. 2490.]
string :  [  116. -2406.  2569.]
s0=116. -2406.  2569.
scanner 10 at position [  116. -2406.  2569.]
string :  [-1173. -1146.  2550.]
s0=-1173. -1146

In [48]:
beacon_poss

array([[ 0.000e+00,  0.000e+00,  0.000e+00],
       [ 1.080e+02, -1.136e+03,  5.700e+01],
       [ 1.040e+02,  6.000e+01,  1.191e+03],
       [ 2.800e+01,  9.900e+01,  2.459e+03],
       [ 5.500e+01, -1.183e+03,  2.527e+03],
       [ 1.010e+02, -2.413e+03,  1.460e+02],
       [ 1.219e+03,  7.900e+01,  2.541e+03],
       [ 1.580e+02,  1.274e+03,  2.455e+03],
       [ 1.860e+02,  2.456e+03,  2.380e+03],
       [ 1.390e+02,  3.642e+03,  2.490e+03],
       [ 1.160e+02, -2.406e+03,  2.569e+03],
       [-1.173e+03, -1.146e+03,  2.550e+03],
       [-2.300e+03, -1.212e+03,  2.377e+03],
       [ 6.700e+01, -2.257e+03,  3.688e+03],
       [-1.094e+03,  1.335e+03,  2.464e+03],
       [-1.128e+03, -2.365e+03,  2.443e+03],
       [ 1.280e+02, -2.387e+03,  1.294e+03],
       [ 1.331e+03, -2.414e+03,  2.418e+03],
       [-1.113e+03,  2.504e+03,  2.563e+03],
       [-1.047e+03,  1.190e+03,  3.745e+03],
       [-1.099e+03,  1.140e+02,  2.497e+03],
       [ 2.556e+03, -4.000e+00,  2.493e+03],
       [-1

In [50]:
maxdistance = 0

for ib0 in range(len(beacon_poss)-1):
    vector0 = beacon_poss[ib0]
    for ib1 in range(ib0+1, len(beacon_poss)):
        vector1 = beacon_poss[ib1]

        dist = getManhatanDistance(vector0,vector1)
        maxdistance=max(dist, maxdistance)

int(maxdistance)

15672