In [79]:
# If I try to use convolution as a method to determine overlap,
# then I will need to create really big arrays, typical size of 2000x2000x2000
# which is not a pratical solution

# Need a function that "convolutes" two different scanner data to find at least 12 overalaps
# Function probably needs to translate second scanner volume
# Only translations that correspond to coordinates of pairs of beacons from each scanner data will be checked

In [80]:
import numpy as np

In [81]:
filename ="data_test.txt"

In [82]:
#Work out a way to read input data
with open(filename,"r") as f:
    lines = f.read().splitlines()

In [83]:
lines

['--- scanner 0 ---',
 '404,-588,-901',
 '528,-643,409',
 '-838,591,734',
 '390,-675,-793',
 '-537,-823,-458',
 '-485,-357,347',
 '-345,-311,381',
 '-661,-816,-575',
 '-876,649,763',
 '-618,-824,-621',
 '553,345,-567',
 '474,580,667',
 '-447,-329,318',
 '-584,868,-557',
 '544,-627,-890',
 '564,392,-477',
 '455,729,728',
 '-892,524,684',
 '-689,845,-530',
 '423,-701,434',
 '7,-33,-71',
 '630,319,-379',
 '443,580,662',
 '-789,900,-551',
 '459,-707,401',
 '',
 '--- scanner 1 ---',
 '686,422,578',
 '605,423,415',
 '515,917,-361',
 '-336,658,858',
 '95,138,22',
 '-476,619,847',
 '-340,-569,-846',
 '567,-361,727',
 '-460,603,-452',
 '669,-402,600',
 '729,430,532',
 '-500,-761,534',
 '-322,571,750',
 '-466,-666,-811',
 '-429,-592,574',
 '-355,545,-477',
 '703,-491,-529',
 '-328,-685,520',
 '413,935,-424',
 '-391,539,-444',
 '586,-435,557',
 '-364,-763,-893',
 '807,-499,-711',
 '755,-354,-619',
 '553,889,-390',
 '',
 '--- scanner 2 ---',
 '649,640,665',
 '682,-795,504',
 '-784,533,-524',
 '-64

In [84]:
scanners = {}

currentscanner = None
beacons_coords = []
for l0 in lines:
    if l0.find("scanner")>=0:
        #next lines are scanner data
        svalue = int(l0.strip("-").strip( ).strip("scanner"))
        currentscanner = svalue
        print(f"New scanner {currentscanner} data")
        scanners[currentscanner]={} #Set new dict value
        beacons_coords=[]
    else:
        if l0=="":
            #End of scanner data
            scanners[currentscanner] =  np.array(beacons_coords)
        else:
            beacons_coords.append( list(map(int,l0.split(","))))

#Store last scanner data
if len(beacons_coords):
     scanners[currentscanner] = np.array(beacons_coords)


New scanner 0 data
New scanner 1 data
New scanner 2 data
New scanner 3 data
New scanner 4 data


In [85]:
scanners

{0: array([[ 404, -588, -901],
        [ 528, -643,  409],
        [-838,  591,  734],
        [ 390, -675, -793],
        [-537, -823, -458],
        [-485, -357,  347],
        [-345, -311,  381],
        [-661, -816, -575],
        [-876,  649,  763],
        [-618, -824, -621],
        [ 553,  345, -567],
        [ 474,  580,  667],
        [-447, -329,  318],
        [-584,  868, -557],
        [ 544, -627, -890],
        [ 564,  392, -477],
        [ 455,  729,  728],
        [-892,  524,  684],
        [-689,  845, -530],
        [ 423, -701,  434],
        [   7,  -33,  -71],
        [ 630,  319, -379],
        [ 443,  580,  662],
        [-789,  900, -551],
        [ 459, -707,  401]]),
 1: array([[ 686,  422,  578],
        [ 605,  423,  415],
        [ 515,  917, -361],
        [-336,  658,  858],
        [  95,  138,   22],
        [-476,  619,  847],
        [-340, -569, -846],
        [ 567, -361,  727],
        [-460,  603, -452],
        [ 669, -402,  600],
        [ 72

In [86]:
scanners[0]

array([[ 404, -588, -901],
       [ 528, -643,  409],
       [-838,  591,  734],
       [ 390, -675, -793],
       [-537, -823, -458],
       [-485, -357,  347],
       [-345, -311,  381],
       [-661, -816, -575],
       [-876,  649,  763],
       [-618, -824, -621],
       [ 553,  345, -567],
       [ 474,  580,  667],
       [-447, -329,  318],
       [-584,  868, -557],
       [ 544, -627, -890],
       [ 564,  392, -477],
       [ 455,  729,  728],
       [-892,  524,  684],
       [-689,  845, -530],
       [ 423, -701,  434],
       [   7,  -33,  -71],
       [ 630,  319, -379],
       [ 443,  580,  662],
       [-789,  900, -551],
       [ 459, -707,  401]])

In [87]:
scanners[1]

array([[ 686,  422,  578],
       [ 605,  423,  415],
       [ 515,  917, -361],
       [-336,  658,  858],
       [  95,  138,   22],
       [-476,  619,  847],
       [-340, -569, -846],
       [ 567, -361,  727],
       [-460,  603, -452],
       [ 669, -402,  600],
       [ 729,  430,  532],
       [-500, -761,  534],
       [-322,  571,  750],
       [-466, -666, -811],
       [-429, -592,  574],
       [-355,  545, -477],
       [ 703, -491, -529],
       [-328, -685,  520],
       [ 413,  935, -424],
       [-391,  539, -444],
       [ 586, -435,  557],
       [-364, -763, -893],
       [ 807, -499, -711],
       [ 755, -354, -619],
       [ 553,  889, -390]])

In [88]:
np.where( (scanners[0] == [ 422, -701,  434]).all(axis=1))[0]

array([], dtype=int64)

In [89]:
def checkOverlapCount(scandata0, scandata1):
    #Check how many beacons ovelap
    #If the data was translated correctly, then there should be at least one overlap
    count=0
    for b0 in scandata0:
        for b1 in scandata1:
            if np.array_equal(b0,b1):
                count+=1
    #print(f"overlap count = {count}")
    return count

In [90]:
def checkOverlapCountOver12(scandata0, scandata1):
    #Check how many beacons ovelap
    #If the data was translated correctly, then there should be at least one overlap
    
    for b1 in scandata1:
        res = np.where( (scandata0 == b1).all(axis=1) )[0]
        if len(res)>0:
            if res[0]>=12:
                return True
    return False

In [91]:
def checkFor12Overlaps(scandata0, scandata1):
    #Parameters scandata0 and scandata1 are the scandata from each, as a numpy array
    #Returns the 3D translation that the 2nd volume needs in order to get 12 beacons to match

    #overlap_scan_data = None

    for beacon0 in scandata0:
        for beacon1 in scandata1:
            #Translate scandata in second volume by vector
            translvector = beacon1-beacon0

            scandata1_transl = scandata1 - translvector #TODO: Check it adds to every row

            #print(f"b0:{beacon0} , b1:{beacon1} ; Translate beacon1 by : {translvector}")
            if checkOverlapCount(scandata0,scandata1_transl)>=12:
                print ("Found >12 overlaps, returning the matched scan data")
                return scandata1_transl, translvector
            else:
                #print("No >12 overlap found")
                pass



In [92]:
#Test
checkFor12Overlaps(scanners[0], scanners[1])

Unfortunately, there's a second problem: the scanners also don't know their rotation or facing direction. Due to magnetic alignment, each scanner is rotated some integer number of 90-degree turns around all of the x, y, and z axes. That is, one scanner might call a direction positive x, while another scanner might call that direction negative y. Or, two scanners might agree on which direction is positive x, but one scanner might be upside-down from the perspective of the other scanner. In total, each scanner could be in any of 24 different orientations: facing positive or negative x, y, or z, and considering any of four directions "up" from that facing.

TODO:
Workout the rotation transform for each scanner orientation
Consider scanner/camera. Camera coordinates: zc - camera pointing at, yc - camera up, xc - other axis
May need to use quaternions to work out rotation transform matrices to apply to each of the vectors

In [31]:
def checkFor12OverlapsInAllOrientations(scandata0,scandata1):
    #Not a correct implementation. Needs to give 24 different ways, not 8cv
    for x_orient in [1,-1]:
        for y_orient in [1,-1]:
            for z_orient in [1,-1]:
                #orient second scandata
                orient_vector = np.array([x_orient,y_orient,z_orient])
                scandata1_orient = scandata1 * orient_vector

                res = checkFor12Overlaps(scandata0,scandata1_orient)
                if not res is None:
                    print (f"x_orient={x_orient} , y_orient={y_orient}, z_orient={z_orient}")
                    return res

In [32]:
# Test
checkFor12OverlapsInAllOrientations(scanners[0], scanners[1])
#This overalap seems to be with second scanner rotated around yy by 180

Found >12 overlaps, returning the matched scan data
x_orient=-1 , y_orient=1, z_orient=-1


(array([[ -618,  -824,  -621],
        [ -537,  -823,  -458],
        [ -447,  -329,   318],
        [  404,  -588,  -901],
        [  -27, -1108,   -65],
        [  544,  -627,  -890],
        [  408, -1815,   803],
        [ -499, -1607,  -770],
        [  528,  -643,   409],
        [ -601, -1648,  -643],
        [ -661,  -816,  -575],
        [  568, -2007,  -577],
        [  390,  -675,  -793],
        [  534, -1912,   768],
        [  497, -1838,  -617],
        [  423,  -701,   434],
        [ -635, -1737,   486],
        [  396, -1931,  -563],
        [ -345,  -311,   381],
        [  459,  -707,   401],
        [ -518, -1681,  -600],
        [  432, -2009,   850],
        [ -739, -1745,   668],
        [ -687, -1600,   576],
        [ -485,  -357,   347]]),
 array([ -68, 1246,   43]))

In [93]:
rotateZBy90Matrix = [   [  0 , -1 ,  0 ] ,
                        [  1 ,  0 ,  0 ] ,
                        [  0 ,  0 ,  1 ]
                    ]

rotateYBy90Matrix = [   [  0 ,  0 ,  1 ] ,
                        [  0 ,  1 ,  0 ] ,
                        [ -1 ,  0 ,  0 ]
                    ]

rotateXByMinus90Matrix = [  [  1 ,  0 ,  0 ] ,
                            [  0 ,  0 ,  1 ] ,
                            [  0 , -1 ,  0 ]
                        ]


In [94]:
#Test
print(np.matmul(rotateZBy90Matrix , [1,0,0])) # expected [0,1,0] #OK
print(np.matmul(rotateYBy90Matrix, [1,0,0])) # expected [0,0,-1] #OK
print(np.matmul(rotateXByMinus90Matrix, [0,1,0])) # expected [0,0,-1] #OK

[0 1 0]
[ 0  0 -1]
[ 0  0 -1]


In [95]:
def applyTransformToScannerData(scannerdata, transfmatrix):
    scannerdata_rot = np.copy(scannerdata)

    for i in range(len(scannerdata)):
        scannerdata_rot[i] = np.matmul(transfmatrix, scannerdata[i])

    return scannerdata_rot

In [96]:
#Test
applyTransformToScannerData(scanners[0], rotateZBy90Matrix)

array([[ 588,  404, -901],
       [ 643,  528,  409],
       [-591, -838,  734],
       [ 675,  390, -793],
       [ 823, -537, -458],
       [ 357, -485,  347],
       [ 311, -345,  381],
       [ 816, -661, -575],
       [-649, -876,  763],
       [ 824, -618, -621],
       [-345,  553, -567],
       [-580,  474,  667],
       [ 329, -447,  318],
       [-868, -584, -557],
       [ 627,  544, -890],
       [-392,  564, -477],
       [-729,  455,  728],
       [-524, -892,  684],
       [-845, -689, -530],
       [ 701,  423,  434],
       [  33,    7,  -71],
       [-319,  630, -379],
       [-580,  443,  662],
       [-900, -789, -551],
       [ 707,  459,  401]])

In [97]:
#Not a correct implementation. Needs to give 24 different ways, not 8cv

def checkFor12OverlapsInAllOrientations2(scandata0,scandata1):
    #Invert or not invert up direction
    for invz in [1,-1]:
        invertmatrix = np.eye(3,3)
        print(f"invz = {invz}")
        if invz==-1:
            invertmatrix[2,2] = -1

        #Rotation around z
        rotZMatrix = np.eye(3,3)
        for izrot in range(4):
            print(f"izrot = {izrot}")
            if izrot >=1:
                rotZMatrix = np.matmul( rotateZBy90Matrix, rotZMatrix)

            #Rotation to face the different axis
            rotFaceDiffAxis = None
            for facerot in ('none', 'ztox', 'ztoy'):
                print(f"facerot = {facerot}")
                scandata1_3 = None
                if facerot=='none':
                    rotFaceDiffAxis = np.eye(3,3)
                elif facerot=='ztox':
                    rotFaceDiffAxis = rotateYBy90Matrix
                elif facerot == 'ztoy':
                    rotFaceDiffAxis = rotateXByMinus90Matrix
                
                transformatrix = np.matmul( rotZMatrix , np.matmul(rotFaceDiffAxis ,invertmatrix) )

                scandata1_trans = applyTransformToScannerData(scandata1, transformatrix)
                #Now we can check for overlaps
                res = checkFor12Overlaps(scandata0, scandata1_trans)
                if not res is None:
                    return res
                

In [98]:
# Use the 'good' match and try to find overlap with rest of scanners
# If no overlap is found, put the scanner data aside, and try again next round.
# Only complete when all scanners have been matched

In [17]:
#This method is not working because the routine
# checkFor12OverlapsInAllOrientations() does not check for 12 orientation possibilities

#Make a copy of all the scanner data

scanners0 = scanners.copy()
sd0 = scanners0[0]
scanners0.pop(0)

wholescan = sd0 # initialises
while len(scanners0)>0:
    scankeys = list(scanners0.keys())
    for scannumb in scankeys:
        print(f"scannumb = {scannumb}")
        res = checkFor12OverlapsInAllOrientations(wholescan, scanners0[scannumb])
        if not res is None:
            overlapscan,transl = res
            print(f"translation = {transl}")
            scanners0.pop(scannumb)
            wholescan = overlapscan

scannumb = 1
Found >12 overlaps, returning the matched scan data
translation = [ -68 1246   43]
scannumb = 2
scannumb = 3
Found >12 overlaps, returning the matched scan data
translation = [  92 2380   20]
scannumb = 4
scannumb = 2
scannumb = 4
scannumb = 2


KeyboardInterrupt: 

In [99]:
#Another faster method
#create all rotation matrices
all24RotationTransforms = []

#Invert or not invert up direction
for invz in [1,-1]:
    invertmatrix = np.eye(3,3)
    #print(f"invz = {invz}")
    if invz==-1:
        #Turn it around by  rotating 180 around yy
        invertmatrix=np.matmul(rotateYBy90Matrix, rotateYBy90Matrix)

    #Rotation around z
    rotZMatrix = np.eye(3,3)
    for izrot in range(4):
        #print(f"izrot = {izrot}")
        if izrot >=1:
            rotZMatrix = np.matmul( rotateZBy90Matrix, rotZMatrix)

        #Rotation to face the different axis
        rotFaceDiffAxis = None
        for facerot in ('none', 'ztox', 'ztoy'):
            #print(f"facerot = {facerot}")
            scandata1_3 = None
            if facerot=='none':
                rotFaceDiffAxis = np.eye(3,3)
            elif facerot=='ztox':
                rotFaceDiffAxis = rotateYBy90Matrix
            elif facerot == 'ztoy':
                rotFaceDiffAxis = rotateXByMinus90Matrix
            
            #transformatrix = np.matmul( rotZMatrix , np.matmul(rotFaceDiffAxis ,invertmatrix) )
            transformatrix = np.matmul( rotFaceDiffAxis , np.matmul(rotZMatrix ,invertmatrix) )

            info = f"invz={invz} ; izrot={izrot} ; facerot={facerot}"

            all24RotationTransforms.append([transformatrix,info])

In [100]:
len(all24RotationTransforms) #size OK

24

In [101]:
all24RotationTransforms

[[array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
  'invz=1 ; izrot=0 ; facerot=none'],
 [array([[ 0.,  0.,  1.],
         [ 0.,  1.,  0.],
         [-1.,  0.,  0.]]),
  'invz=1 ; izrot=0 ; facerot=ztox'],
 [array([[ 1.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0., -1.,  0.]]),
  'invz=1 ; izrot=0 ; facerot=ztoy'],
 [array([[ 0., -1.,  0.],
         [ 1.,  0.,  0.],
         [ 0.,  0.,  1.]]),
  'invz=1 ; izrot=1 ; facerot=none'],
 [array([[0., 0., 1.],
         [1., 0., 0.],
         [0., 1., 0.]]),
  'invz=1 ; izrot=1 ; facerot=ztox'],
 [array([[ 0., -1.,  0.],
         [ 0.,  0.,  1.],
         [-1.,  0.,  0.]]),
  'invz=1 ; izrot=1 ; facerot=ztoy'],
 [array([[-1.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0.,  1.]]),
  'invz=1 ; izrot=2 ; facerot=none'],
 [array([[ 0.,  0.,  1.],
         [ 0., -1.,  0.],
         [ 1.,  0.,  0.]]),
  'invz=1 ; izrot=2 ; facerot=ztox'],
 [array([[-1.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0.,  1.,  0

In [102]:
#Test all rotation on a set of vectors
test_vector_list = np.array (
    [ [-1,-1,1],
    [-2,-2,2],
    [-3,-3,3],
    [-2,-3,1],
    [5,6,-4],
    [8,0,7],
    ]
)
for transform , info in all24RotationTransforms:
    scandata1_trans = applyTransformToScannerData(test_vector_list, transform)
    
    print(info)
    print(scandata1_trans)

    #OK, consistent with problem example

invz=1 ; izrot=0 ; facerot=none
[[-1 -1  1]
 [-2 -2  2]
 [-3 -3  3]
 [-2 -3  1]
 [ 5  6 -4]
 [ 8  0  7]]
invz=1 ; izrot=0 ; facerot=ztox
[[ 1 -1  1]
 [ 2 -2  2]
 [ 3 -3  3]
 [ 1 -3  2]
 [-4  6 -5]
 [ 7  0 -8]]
invz=1 ; izrot=0 ; facerot=ztoy
[[-1  1  1]
 [-2  2  2]
 [-3  3  3]
 [-2  1  3]
 [ 5 -4 -6]
 [ 8  7  0]]
invz=1 ; izrot=1 ; facerot=none
[[ 1 -1  1]
 [ 2 -2  2]
 [ 3 -3  3]
 [ 3 -2  1]
 [-6  5 -4]
 [ 0  8  7]]
invz=1 ; izrot=1 ; facerot=ztox
[[ 1 -1 -1]
 [ 2 -2 -2]
 [ 3 -3 -3]
 [ 1 -2 -3]
 [-4  5  6]
 [ 7  8  0]]
invz=1 ; izrot=1 ; facerot=ztoy
[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 3  1  2]
 [-6 -4 -5]
 [ 0  7 -8]]
invz=1 ; izrot=2 ; facerot=none
[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 2  3  1]
 [-5 -6 -4]
 [-8  0  7]]
invz=1 ; izrot=2 ; facerot=ztox
[[ 1  1 -1]
 [ 2  2 -2]
 [ 3  3 -3]
 [ 1  3 -2]
 [-4 -6  5]
 [ 7  0  8]]
invz=1 ; izrot=2 ; facerot=ztoy
[[ 1  1 -1]
 [ 2  2 -2]
 [ 3  3 -3]
 [ 2  1 -3]
 [-5 -4  6]
 [-8  7  0]]
invz=1 ; izrot=3 ; facerot=none
[[-1  1  1]
 [-2  2  2]

In [103]:
def checkFor12OverlapsInAllOrientations3(scandata0,scandata1):
    for transform , info in all24RotationTransforms:
        scandata1_trans = applyTransformToScannerData(scandata1, transform)
        
        #Now we can check for overlaps
        res = checkFor12Overlaps(scandata0, scandata1_trans)
        if not res is None:
            print(f"Overlap found with {info} , translate: {res[1]}")
            return res

In [104]:
#Try manually
#Problem says that scanner 0 overlaps with scanner 1
# and scanner 4 overalaps with scanner 1

In [105]:
checkFor12OverlapsInAllOrientations3(scanners[0], scanners[1])

Found >12 overlaps, returning the matched scan data
Overlap found with invz=-1 ; izrot=0 ; facerot=none , translate: [ -68 1246   43]


(array([[ -618,  -824,  -621],
        [ -537,  -823,  -458],
        [ -447,  -329,   318],
        [  404,  -588,  -901],
        [  -27, -1108,   -65],
        [  544,  -627,  -890],
        [  408, -1815,   803],
        [ -499, -1607,  -770],
        [  528,  -643,   409],
        [ -601, -1648,  -643],
        [ -661,  -816,  -575],
        [  568, -2007,  -577],
        [  390,  -675,  -793],
        [  534, -1912,   768],
        [  497, -1838,  -617],
        [  423,  -701,   434],
        [ -635, -1737,   486],
        [  396, -1931,  -563],
        [ -345,  -311,   381],
        [  459,  -707,   401],
        [ -518, -1681,  -600],
        [  432, -2009,   850],
        [ -739, -1745,   668],
        [ -687, -1600,   576],
        [ -485,  -357,   347]]),
 array([ -68, 1246,   43]))

In [106]:
checkFor12OverlapsInAllOrientations3(scanners[1], scanners[4])

Found >12 overlaps, returning the matched scan data
Overlap found with invz=-1 ; izrot=3 ; facerot=ztoy , translate: [ -88 -113 1104]


(array([[  680,  -449, -1831],
        [ -466,  -666,  -811],
        [  699,   574, -1545],
        [  553,   889,  -390],
        [  515,   917,  -361],
        [ -391,   539,  -444],
        [ -544,  -347, -1936],
        [ -397,   551, -2031],
        [  481,   619, -1512],
        [  524,   625, -1570],
        [  104,   -38, -1214],
        [ -340,  -569,  -846],
        [  807,  -499,  -711],
        [ -364,  -763,  -893],
        [ -388,   706, -1912],
        [  703,  -491,  -529],
        [  755,  -354,  -619],
        [  413,   935,  -424],
        [ -355,   545,  -477],
        [ -459,   722, -1976],
        [  600,  -469, -1937],
        [  692,  -374, -1911],
        [ -428,  -338, -1943],
        [ -537,  -419, -1995],
        [ -460,   603,  -452],
        [   42,   127, -1134]]),
 array([ -88, -113, 1104]))

In [60]:
#This method uses the dictionary with all possible scanner transformations
#Make a copy of all the scanner data
iscannersleft = list(np.arange(1,len(scanners)))
iscannersleft

[1, 2, 3, 4]

In [ ]:
def appendScannersAndRemoveDuplicates(scanner0, scanner1):
    scanner_ret = np.copy(scanner0)
    for b1 in scanner1:
        #Check if duplicate

In [65]:
iscannersleft = list(np.arange(1,len(scanners)))

wholescan = np.copy(scanners[0]) # initialises
while len(iscannersleft)>0:
    iscannersleft0 = iscannersleft.copy()
    for scannumb in iscannersleft0:
        print(f"scanner_numb = {scannumb}")
        #res = checkFor12OverlapsInAllOrientations2(wholescan, scanners0[scannumb])
        res = checkFor12OverlapsInAllOrientations3(wholescan, scanners[scannumb])
        if not res is None:
            scanner_adj,transl = res
            #print(f"translation = {transl}")
            wholescan = np.append(wholescan, scanner_adj, axis=0)
            #need to remove duplicates
            assert wholescan.shape[1] ==3, "Error wholescan.shape not =3"
            iscannersleft.remove(scannumb)

scanner_numb = 1
Found >12 overlaps, returning the matched scan data
Overlap found with invz=-1 ; izrot=0 ; facerot=none , translate: [ -68 1246   43]
scanner_numb = 2
scanner_numb = 3
Found >12 overlaps, returning the matched scan data
Overlap found with invz=-1 ; izrot=0 ; facerot=none , translate: [  92 2380   20]
scanner_numb = 4
Found >12 overlaps, returning the matched scan data
Overlap found with invz=-1 ; izrot=1 ; facerot=ztoy , translate: [   20  1133 -1061]
scanner_numb = 2
Found >12 overlaps, returning the matched scan data
Overlap found with invz=1 ; izrot=2 ; facerot=ztoy , translate: [-1105  1205 -1229]
