In [1]:
#filename = "data_test.txt"
filename = "data.txt"

In [2]:
with open(filename,"r") as f:
    lines = f.read().splitlines() #better than readlines because it removes the return character

In [3]:
lines

['1443582148',
 '6553734851',
 '1451741246',
 '8835218864',
 '1662317262',
 '1731656623',
 '1128178367',
 '5842351665',
 '6677326843',
 '7381433267']

In [4]:
data0=[]
for l in lines:
    l0=l.strip()
    dataline = [int(char) for char in l0]
    data0.append(dataline)

In [5]:
data0

[[1, 4, 4, 3, 5, 8, 2, 1, 4, 8],
 [6, 5, 5, 3, 7, 3, 4, 8, 5, 1],
 [1, 4, 5, 1, 7, 4, 1, 2, 4, 6],
 [8, 8, 3, 5, 2, 1, 8, 8, 6, 4],
 [1, 6, 6, 2, 3, 1, 7, 2, 6, 2],
 [1, 7, 3, 1, 6, 5, 6, 6, 2, 3],
 [1, 1, 2, 8, 1, 7, 8, 3, 6, 7],
 [5, 8, 4, 2, 3, 5, 1, 6, 6, 5],
 [6, 6, 7, 7, 3, 2, 6, 8, 4, 3],
 [7, 3, 8, 1, 4, 3, 3, 2, 6, 7]]

In [6]:
import numpy as np
data = np.array(data0, dtype=np.int32)

In [7]:
data.shape

(10, 10)

In [8]:
hasFlashed = np.zeros(data.shape, dtype=np.int32)
hasFlashed

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
def incrementElemAt(y,x):
    if hasFlashed[y,x]==0:
        
        data[y,x] += 1 #Increment
        #print(f"increment {y},{x} to {data[y,x]}")

        #Check if flashed and process it
        if data[y,x] >9:
            hasFlashed[y,x] = 1
            #print(f"Flash element {y},{x}")
            #Increment values around

            data[y,x]=0 #Set to zero here

            if y>0: #row above
                incrementElemAt(y-1,x)
                if x>0:
                    incrementElemAt(y-1, x-1)
                if x<9:
                    incrementElemAt(y-1,x+1)
            if y<9: #row below
                incrementElemAt(y+1,x)
                if x>0:
                    incrementElemAt(y+1, x-1)
                if x<9:
                    incrementElemAt(y+1,x+1)
            
            if x>0: #middle row
                incrementElemAt(y, x-1)
            if x<9:
                incrementElemAt(y,x+1)


In [10]:
def doStep():
    #Reset flashes
    #hasFlashed = np.zeros(data.shape, dtype=np.int32)
    hasFlashed.fill(0)

    for iy in range(10):
        for ix in range(10):
            print(f"iy,ix = {iy},{ix}")
            incrementElemAt(iy,ix)
    
    #When complete, get the number of flashes

    stepFlashes = np.sum(hasFlashed)
    print(f"stepFlashes = {stepFlashes}")
    return stepFlashes

In [11]:
totalflashes = 0
for steps in range(100):
    stepflashes = doStep()
    totalflashes+=stepflashes

iy,ix = 0,0
iy,ix = 0,1
iy,ix = 0,2
iy,ix = 0,3
iy,ix = 0,4
iy,ix = 0,5
iy,ix = 0,6
iy,ix = 0,7
iy,ix = 0,8
iy,ix = 0,9
iy,ix = 1,0
iy,ix = 1,1
iy,ix = 1,2
iy,ix = 1,3
iy,ix = 1,4
iy,ix = 1,5
iy,ix = 1,6
iy,ix = 1,7
iy,ix = 1,8
iy,ix = 1,9
iy,ix = 2,0
iy,ix = 2,1
iy,ix = 2,2
iy,ix = 2,3
iy,ix = 2,4
iy,ix = 2,5
iy,ix = 2,6
iy,ix = 2,7
iy,ix = 2,8
iy,ix = 2,9
iy,ix = 3,0
iy,ix = 3,1
iy,ix = 3,2
iy,ix = 3,3
iy,ix = 3,4
iy,ix = 3,5
iy,ix = 3,6
iy,ix = 3,7
iy,ix = 3,8
iy,ix = 3,9
iy,ix = 4,0
iy,ix = 4,1
iy,ix = 4,2
iy,ix = 4,3
iy,ix = 4,4
iy,ix = 4,5
iy,ix = 4,6
iy,ix = 4,7
iy,ix = 4,8
iy,ix = 4,9
iy,ix = 5,0
iy,ix = 5,1
iy,ix = 5,2
iy,ix = 5,3
iy,ix = 5,4
iy,ix = 5,5
iy,ix = 5,6
iy,ix = 5,7
iy,ix = 5,8
iy,ix = 5,9
iy,ix = 6,0
iy,ix = 6,1
iy,ix = 6,2
iy,ix = 6,3
iy,ix = 6,4
iy,ix = 6,5
iy,ix = 6,6
iy,ix = 6,7
iy,ix = 6,8
iy,ix = 6,9
iy,ix = 7,0
iy,ix = 7,1
iy,ix = 7,2
iy,ix = 7,3
iy,ix = 7,4
iy,ix = 7,5
iy,ix = 7,6
iy,ix = 7,7
iy,ix = 7,8
iy,ix = 7,9
iy,ix = 8,0
iy,ix = 8,1
iy,ix = 8,2
iy,i

In [12]:
totalflashes

1717

## Test

In [11]:
#first step
doStep()

iy,ix = 0,0
increment 0,0 to 6
iy,ix = 0,1
increment 0,1 to 5
iy,ix = 0,2
increment 0,2 to 9
iy,ix = 0,3
increment 0,3 to 4
iy,ix = 0,4
increment 0,4 to 2
iy,ix = 0,5
increment 0,5 to 5
iy,ix = 0,6
increment 0,6 to 4
iy,ix = 0,7
increment 0,7 to 3
iy,ix = 0,8
increment 0,8 to 3
iy,ix = 0,9
increment 0,9 to 4
iy,ix = 1,0
increment 1,0 to 3
iy,ix = 1,1
increment 1,1 to 8
iy,ix = 1,2
increment 1,2 to 5
iy,ix = 1,3
increment 1,3 to 6
iy,ix = 1,4
increment 1,4 to 9
iy,ix = 1,5
increment 1,5 to 6
iy,ix = 1,6
increment 1,6 to 5
iy,ix = 1,7
increment 1,7 to 8
iy,ix = 1,8
increment 1,8 to 2
iy,ix = 1,9
increment 1,9 to 2
iy,ix = 2,0
increment 2,0 to 6
iy,ix = 2,1
increment 2,1 to 3
iy,ix = 2,2
increment 2,2 to 7
iy,ix = 2,3
increment 2,3 to 5
iy,ix = 2,4
increment 2,4 to 6
iy,ix = 2,5
increment 2,5 to 6
iy,ix = 2,6
increment 2,6 to 7
iy,ix = 2,7
increment 2,7 to 2
iy,ix = 2,8
increment 2,8 to 8
iy,ix = 2,9
increment 2,9 to 4
iy,ix = 3,0
increment 3,0 to 7
iy,ix = 3,1
increment 3,1 to 2
iy,ix = 

In [12]:
data

array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
       [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
       [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
       [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
       [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
       [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
       [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
       [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
       [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
       [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]])

In [13]:
hasFlashed

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
#second step
doStep() #not working

iy,ix = 0,0
increment 0,0 to 7
iy,ix = 0,1
increment 0,1 to 6
iy,ix = 0,2
increment 0,2 to 10
Flash element 0,2
increment 1,2 to 6
increment 1,1 to 9
increment 1,3 to 7
increment 0,1 to 7
increment 0,3 to 5
iy,ix = 0,3
increment 0,3 to 6
iy,ix = 0,4
increment 0,4 to 3
iy,ix = 0,5
increment 0,5 to 6
iy,ix = 0,6
increment 0,6 to 5
iy,ix = 0,7
increment 0,7 to 4
iy,ix = 0,8
increment 0,8 to 4
iy,ix = 0,9
increment 0,9 to 5
iy,ix = 1,0
increment 1,0 to 4
iy,ix = 1,1
increment 1,1 to 10
Flash element 1,1
increment 0,1 to 8
increment 0,0 to 8
increment 2,1 to 4
increment 2,0 to 7
increment 2,2 to 8
increment 1,0 to 5
increment 1,2 to 7
iy,ix = 1,2
increment 1,2 to 8
iy,ix = 1,3
increment 1,3 to 8
iy,ix = 1,4
increment 1,4 to 10
Flash element 1,4
increment 0,4 to 4
increment 0,3 to 7
increment 0,5 to 7
increment 2,4 to 7
increment 2,3 to 6
increment 2,5 to 7
increment 1,3 to 9
increment 1,5 to 7
iy,ix = 1,5
increment 1,5 to 8
iy,ix = 1,6
increment 1,6 to 6
iy,ix = 1,7
increment 1,7 to 9
iy,ix

In [15]:
data #not consistent with problem

array([[8, 8, 0, 7, 4, 7, 6, 5, 5, 5],
       [5, 0, 8, 9, 0, 8, 7, 0, 5, 4],
       [8, 5, 9, 7, 8, 8, 9, 6, 0, 8],
       [8, 4, 8, 5, 7, 6, 9, 6, 0, 0],
       [8, 7, 0, 0, 9, 0, 8, 8, 0, 0],
       [6, 6, 0, 0, 0, 8, 8, 9, 8, 9],
       [6, 8, 0, 0, 0, 0, 5, 9, 4, 3],
       [0, 0, 0, 0, 0, 0, 7, 4, 5, 6],
       [9, 0, 0, 0, 0, 0, 0, 8, 7, 6],
       [8, 7, 0, 0, 0, 0, 6, 8, 4, 8]])