# Read file as lines

In [1]:
TEST = False
TEST_SOLUTION = 480

INPUT_FN = "input_test.txt"

if not TEST:
    INPUT_FN = "input.txt" # 1477762

with open(INPUT_FN) as f:
    lines = [l.rstrip() for l in f]

if lines[-1]=='':
    lines=lines[:,-1]

In [2]:
lines

['Button A: X+65, Y+11',
 'Button B: X+56, Y+64',
 'Prize: X=7499, Y=5849',
 '',
 'Button A: X+23, Y+55',
 'Button B: X+37, Y+13',
 'Prize: X=10808, Y=4864',
 '',
 'Button A: X+62, Y+48',
 'Button B: X+38, Y+93',
 'Prize: X=6578, Y=10497',
 '',
 'Button A: X+48, Y+42',
 'Button B: X+18, Y+72',
 'Prize: X=3534, Y=7536',
 '',
 'Button A: X+11, Y+75',
 'Button B: X+74, Y+18',
 'Prize: X=14353, Y=1985',
 '',
 'Button A: X+51, Y+21',
 'Button B: X+44, Y+75',
 'Prize: X=8260, Y=12662',
 '',
 'Button A: X+20, Y+68',
 'Button B: X+59, Y+11',
 'Prize: X=15354, Y=9546',
 '',
 'Button A: X+43, Y+70',
 'Button B: X+48, Y+23',
 'Prize: X=654, Y=9559',
 '',
 'Button A: X+73, Y+28',
 'Button B: X+21, Y+66',
 'Prize: X=15091, Y=376',
 '',
 'Button A: X+46, Y+14',
 'Button B: X+38, Y+78',
 'Prize: X=12952, Y=13720',
 '',
 'Button A: X+16, Y+47',
 'Button B: X+61, Y+38',
 'Prize: X=18507, Y=9391',
 '',
 'Button A: X+65, Y+33',
 'Button B: X+22, Y+52',
 'Prize: X=5703, Y=13797',
 '',
 'Button A: X+69, Y+

In [3]:
from dataclasses import dataclass
@dataclass
class cMachine:
    prize: tuple[int,int]
    button_A: tuple[int,int]
    button_B: tuple[int,int]

# Parse file lines

In [4]:
machines=[]

button_A=None
button_B=None
prize = None

for sline in lines:
    if len(sline)>0:
        if "Button A" in sline:
            split0 = sline.split(": ")
            split1 = split0[1].split(",")
            x,y = [ int(chars.split('+')[1]) for chars in split1]
            button_A = (x,y)
        
        elif "Button B" in sline:
            split0 = sline.split(": ")
            split1 = split0[1].split(",")
            x,y = [ int(chars.split('+')[1]) for chars in split1]
            button_B = (x,y)
        elif "Prize" in sline:
            split0 = sline.split(": ")
            split1 = split0[1].split(",")
            x,y = [ int(chars.split('=')[1]) for chars in split1]
            prize = (x,y)

            cmach0 = cMachine(prize, button_A, button_B)
            machines.append(cmach0)
    


In [5]:
machines

[cMachine(prize=(7499, 5849), button_A=(65, 11), button_B=(56, 64)),
 cMachine(prize=(10808, 4864), button_A=(23, 55), button_B=(37, 13)),
 cMachine(prize=(6578, 10497), button_A=(62, 48), button_B=(38, 93)),
 cMachine(prize=(3534, 7536), button_A=(48, 42), button_B=(18, 72)),
 cMachine(prize=(14353, 1985), button_A=(11, 75), button_B=(74, 18)),
 cMachine(prize=(8260, 12662), button_A=(51, 21), button_B=(44, 75)),
 cMachine(prize=(15354, 9546), button_A=(20, 68), button_B=(59, 11)),
 cMachine(prize=(654, 9559), button_A=(43, 70), button_B=(48, 23)),
 cMachine(prize=(15091, 376), button_A=(73, 28), button_B=(21, 66)),
 cMachine(prize=(12952, 13720), button_A=(46, 14), button_B=(38, 78)),
 cMachine(prize=(18507, 9391), button_A=(16, 47), button_B=(61, 38)),
 cMachine(prize=(5703, 13797), button_A=(65, 33), button_B=(22, 52)),
 cMachine(prize=(8429, 4387), button_A=(69, 27), button_B=(15, 65)),
 cMachine(prize=(4962, 8890), button_A=(46, 20), button_B=(36, 54)),
 cMachine(prize=(18784, 17

For each check if prize is reachable. Use linalg.solve

In [6]:
mach0= machines[0]

In [7]:
mach0

cMachine(prize=(7499, 5849), button_A=(65, 11), button_B=(56, 64))

In [8]:
from numpy.linalg import solve
import numpy as np


In [9]:
A = np.transpose(np.array( [mach0.button_A, mach0.button_B]))
A

array([[65, 56],
       [11, 64]])

In [10]:
B = np.array(mach0.prize)
B

array([7499, 5849])

In [11]:
X = solve( A ,  B)
X

array([43., 84.])

OK

In [12]:
def is_all_int(A):
    if np.allclose(np.rint(A),A):
        return True
    return False

In [13]:
is_all_int(X)

True

# Algorithm to calculate tokens

In [14]:
int(np.inner([60.,9.],[3,1]))

189

In [15]:
count_tokens=0

for mach0 in machines:
    # check if buttons do the same, only different lengths
    if mach0.button_A[1]>0 and mach0.button_B[1]>0:
        if mach0.button_A[0]/ mach0.button_A[1] == mach0.button_B[0]/ mach0.button_B[1]:
            print("THE SAME DIRECTION")
    A = np.transpose(np.array( [mach0.button_A, mach0.button_B]))
    B = np.array(mach0.prize)
    X = solve( A ,  B)
    print(f"Machine  ButtA: {mach0.button_A}, ButtB: {mach0.button_B}, Pr: {mach0.prize}")
    if is_all_int(X):
        #print("is_all_int")
        # Check tokens don't exceed 100
        if np.max(X)<=100:
            count_tokens+= np.rint(np.inner(X,[3,1])) #int does what floor does, so it may sometimes give -1 value
            print(f"OK:{X} {count_tokens}")
        else:
            print(f"Too many button presses : {X}")
    else:
        print(f"not all int {X}")


Machine  ButtA: (65, 11), ButtB: (56, 64), Pr: (7499, 5849)
OK:[43. 84.] 213.0
Machine  ButtA: (23, 55), ButtB: (37, 13), Pr: (10808, 4864)
not all int [ 22.73271889 277.97695853]
Machine  ButtA: (62, 48), ButtB: (38, 93), Pr: (6578, 10497)
OK:[54. 85.] 460.0
Machine  ButtA: (48, 42), ButtB: (18, 72), Pr: (3534, 7536)
OK:[44. 79.] 671.0
Machine  ButtA: (11, 75), ButtB: (74, 18), Pr: (14353, 1985)
not all int [-20.82660688 197.05530643]
Machine  ButtA: (51, 21), ButtB: (44, 75), Pr: (8260, 12662)
not all int [ 21.50017235 162.80661841]
Machine  ButtA: (20, 68), ButtB: (59, 11), Pr: (15354, 9546)
not all int [103.98734177 224.98734177]
Machine  ButtA: (43, 70), ButtB: (48, 23), Pr: (654, 9559)
not all int [ 187.17418811 -154.05187685]
Machine  ButtA: (73, 28), ButtB: (21, 66), Pr: (15091, 376)
not all int [233.59574468 -93.40425532]
Machine  ButtA: (46, 14), ButtB: (38, 78), Pr: (12952, 13720)
not all int [159.97905759 147.18324607]
Machine  ButtA: (16, 47), ButtB: (61, 38), Pr: (18507, 

In [16]:
count_tokens

np.float64(31623.0)

In [17]:
if TEST:
    assert count_tokens == TEST_SOLUTION

# Part 2

Cannot use numpy to solve this as numpy uses int approximations for large numbers

In [52]:
#prize_add = 1 # debug
prize_add = 10000000000000

In [53]:
count_tokens=0

for mach0 in machines:
    # check if buttons do the same, only different lengths
    ax,ay = mach0.button_A
    bx,by = mach0.button_B
    tx,ty = mach0.prize

    tx+= prize_add
    ty+= prize_add

    nb = (ax*ty - ay*tx) / (ax*by-ay*bx)
    na = (tx-bx*nb)/ax
    
    print(f"Machine  ButtA: {mach0.button_A}, ButtB: {mach0.button_B}, Pr: {mach0.prize}")
    if na>0 and na.is_integer() and nb>0 and nb.is_integer():
        count_tokens+= int(na)*3 + int(nb)
        print(f"OK:{na, nb} {count_tokens}")
    else:
        print(f"not all int {na,nb}")

Machine  ButtA: (65, 11), ButtB: (56, 64), Pr: (7499, 5849)
not all int (22573363474.151245, 152370203244.27087)
Machine  ButtA: (23, 55), ButtB: (37, 13), Pr: (10808, 4864)
OK:(138248847949.0, 184331797513.0) 599078341360
Machine  ButtA: (62, 48), ButtB: (38, 93), Pr: (6578, 10497)
not all int (139523084782.56418, 35514967106.81634)
Machine  ButtA: (48, 42), ButtB: (18, 72), Pr: (3534, 7536)
not all int (200000000044.0, 22222222301.22222)
Machine  ButtA: (11, 75), ButtB: (74, 18), Pr: (14353, 1985)
OK:(104633781743.0, 119581465070.0) 1032561151659
Machine  ButtA: (51, 21), ButtB: (44, 75), Pr: (8260, 12662)
OK:(106859703572.0, 103412616502.0) 1456552878877
Machine  ButtA: (20, 68), ButtB: (59, 11), Pr: (15354, 9546)
OK:(126582278585.0, 126582278706.0) 1962881993338
Machine  ButtA: (43, 70), ButtB: (48, 23), Pr: (654, 9559)
OK:(105440742490.0, 113876001533.0) 2393080222341
Machine  ButtA: (73, 28), ButtB: (21, 66), Pr: (15091, 376)
OK:(106382978957.0, 106382978630.0) 2818612137842
Mach

In [54]:
count_tokens

93209116744825